// ─── Exercise Guide Library ───────────────────────────────────────────────────
//
// Static coaching content for the exercise library: how to set up, how to
// finish, how to perform, coaching tips, common mistakes, and when to use
// each movement. Written from a DPT / strength-coach perspective for runners.
//
// Keyed by canonical slug; EXERCISE_GUIDE_ALIASES maps the ids used by the
// strength engine catalogue (`squat_goblet`), the exercise store (`b_*`), and
// the prototype strength screen (`gs`, `rdl`, …) onto those slugs so every
// surface shares one source of coaching truth.

export type ExerciseGuide = {
  startPosition:  string;
  finishPosition: string;
  howTo:          string;
  tips:           string[];
  mistakes:       string[];
  whenToUse:      string;
};

const GUIDES: Record<string, ExerciseGuide> = {
  goblet_squat: {
    startPosition:  'Stand feet shoulder-width, toes slightly out, dumbbell or kettlebell held vertically against the chest with elbows tucked.',
    finishPosition: 'Thighs at or just below parallel, chest tall, heels down, knees tracking over the middle of the feet.',
    howTo:          'Brace, sit down between the hips, keep the weight glued to the chest, then drive the whole foot into the floor to stand.',
    tips:           ['Let the elbows slide inside the knees at the bottom — it keeps the torso upright.', 'Control 2–3 seconds down; stand up with intent.'],
    mistakes:       ['Heels lifting because the descent is knees-first instead of hips-and-knees together.', 'Letting the weight drift away from the chest, which tips the torso forward.'],
    whenToUse:      'The default runner squat: loads the quads and glutes with minimal spinal load and teaches upright squat mechanics.',
  },
  bulgarian_split_squat: {
    startPosition:  'Rear foot laces-down on a bench, front foot far enough forward that the front shin stays near vertical at the bottom.',
    finishPosition: 'Rear knee just above the floor, front thigh near parallel, hips square and torso slightly forward.',
    howTo:          'Lower the rear knee straight down, keep most of the weight on the front leg, and press through the front heel to stand.',
    tips:           ['Slight forward torso lean biases the glutes and spares the knee.', 'Hold dumbbells at the sides only after bodyweight is smooth.'],
    mistakes:       ['Front foot too close, driving the knee far past the toes with heel lift.', 'Pushing off the back foot instead of working the front leg.'],
    whenToUse:      'Top-tier single-leg strength for runners — big glute and quad stimulus that also exposes side-to-side differences.',
  },
  box_squat: {
    startPosition:  'Stand in front of a box or bench at knee height, feet shoulder-width, arms out for counterbalance.',
    finishPosition: 'Seated lightly on the box with shins vertical and torso braced — do not fully relax.',
    howTo:          'Push the hips back, touch the box under control without plopping, pause one beat, then stand without rocking.',
    tips:           ['Treat the box as a depth gauge, not a chair.', 'Raise the box height if control is shaky, lower it as you improve.'],
    mistakes:       ['Dropping the last few inches and letting the box catch you.', 'Rocking forward to generate momentum on the way up.'],
    whenToUse:      'A squat regression for early strength phases, returning from injury, or grooving depth with confidence.',
  },
  romanian_deadlift: {
    startPosition:  'Stand tall holding the bar or dumbbells at the thighs, feet hip-width, soft bend in the knees.',
    finishPosition: 'Load just below the knees (hamstring-stretch depth), hips back, spine long, shoulders over the bar.',
    howTo:          'Push the hips straight back while the load slides down the thighs. When the hamstrings load up, stand by driving the hips forward.',
    tips:           ['The knees stay softly bent the whole time — this is a hinge, not a squat.', 'Finish standing tall by squeezing the glutes, not leaning back.'],
    mistakes:       ['Rounding the low back to chase depth beyond hamstring flexibility.', 'Bending the knees more as the weight lowers, turning it into a squat.'],
    whenToUse:      'The primary posterior-chain builder: hamstring and glute strength that directly supports stride power and hamstring durability.',
  },
  single_leg_rdl: {
    startPosition:  'Stand on one leg with a soft knee, dumbbell in the opposite hand, free leg ready to travel back.',
    finishPosition: 'Torso and rear leg near one straight line parallel to the floor, hips level, weight hanging under the shoulder.',
    howTo:          'Hinge at the standing hip while the free leg counterbalances behind. Keep the pelvis square, then return by driving the standing hip forward.',
    tips:           ['Point the rear-foot toes at the floor to keep the hips from opening.', 'Use a fingertip on a wall for balance before adding load.'],
    mistakes:       ['Rotating the pelvis open toward the free-leg side.', 'Rushing the descent and losing balance instead of owning the hinge.'],
    whenToUse:      'Single-leg hamstring strength plus balance — the closest gym match to the demands of stance phase in running.',
  },
  hip_thrust: {
    startPosition:  'Upper back on a bench, feet flat about hip-width, bar or dumbbell over the hips, chin gently tucked.',
    finishPosition: 'Hips locked out level with the shoulders and knees, shins vertical, ribs down.',
    howTo:          'Drive through the heels, squeeze the glutes to lift the hips to full extension, hold one second, lower with control.',
    tips:           ['Posteriorly tuck the pelvis slightly at the top — finish with glutes, not low back.', 'Eyes forward, not at the ceiling, keeps the ribs stacked.'],
    mistakes:       ['Hyperextending the spine past hip lockout.', 'Feet too far forward so the hamstrings cramp and take over.'],
    whenToUse:      'Maximal glute loading with almost no spinal or knee stress — hip extension power for the push-off phase.',
  },
  nordic_curl: {
    startPosition:  'Kneel on a pad with ankles anchored, body in one line from knees to head, arms ready to catch.',
    finishPosition: 'Torso lowered as far toward the floor as the hamstrings can control, hips still extended.',
    howTo:          'Lower the whole body forward as slowly as possible using the hamstrings as brakes, catch with the hands, push back lightly to return.',
    tips:           ['Even 3–4 controlled reps is a strong stimulus — quality beats quantity.', 'Keep the hips extended; folding at the hips unloads the hamstrings.'],
    mistakes:       ['Breaking at the hips so the exercise becomes an arm catch.', 'Doing too many reps too soon — expect real soreness at first.'],
    whenToUse:      'The best-evidenced hamstring-injury-prevention exercise in sport. Use in low doses year-round.',
  },
  reverse_lunge: {
    startPosition:  'Stand tall, feet hip-width, dumbbells at the sides or hands on hips.',
    finishPosition: 'Rear knee just above the floor, front shin near vertical, torso upright with slight forward lean.',
    howTo:          'Step back into a stable split, lower the back knee straight down, then push through the front foot to return to standing.',
    tips:           ['Step back far enough that the front knee stays over the mid-foot.', 'Think "elevator down," not "drift forward."'],
    mistakes:       ['Short, choppy steps that slam the front knee forward.', 'Wobbling because the feet land on a tightrope — keep hip-width rails.'],
    whenToUse:      'Knee-friendlier than forward lunges: single-leg strength with less braking stress at the patellofemoral joint.',
  },
  lateral_lunge: {
    startPosition:  'Stand tall with feet together, hands at the chest for counterbalance.',
    finishPosition: 'One leg bent with hips sitting back over that heel, the other leg straight, both feet flat and toes forward.',
    howTo:          'Step wide to one side, push the hips back over the stepping leg, keep the trail leg straight, then drive back to the start.',
    tips:           ['Sit back like a single-leg box squat, not forward over the knee.', 'Keep both feet pointing ahead to load the adductors properly.'],
    mistakes:       ['Knee collapsing inward on the working leg.', 'Bending forward at the spine instead of hinging at the hip.'],
    whenToUse:      'Trains the frontal plane runners never visit: adductor and lateral hip strength that protects the groin and knees.',
  },
  step_up: {
    startPosition:  'Face a knee-height box with one full foot planted on it, hips square.',
    finishPosition: 'Standing fully upright on top of the box, trailing knee driving up, working leg locked out.',
    howTo:          'Press through the whole top foot and stand up in one piece; the bottom leg gives as little push as possible. Lower down with control.',
    tips:           ['The slower the lower-down, the more the exercise gives you.', 'Choose a height where the top thigh starts near parallel.'],
    mistakes:       ['Bouncing off the bottom leg like a spring.', 'Letting the top knee dive inward as you stand.'],
    whenToUse:      'Concentric single-leg drive that mirrors hill running; simple to load and easy on the knees.',
  },
  push_up: {
    startPosition:  'High plank: hands under shoulders, body rigid from head to heels, glutes and abs braced.',
    finishPosition: 'Chest about a fist-height from the floor, elbows tracking about 45 degrees from the torso, body still one line.',
    howTo:          'Lower the whole body as one unit, pause briefly just off the floor, and press back to the top without the hips sagging or hiking.',
    tips:           ['Screw the hands outward into the floor — it packs the shoulders.', 'Elevate the hands on a bench to scale, rather than dropping the knees.'],
    mistakes:       ['Hips sagging into a banana at the bottom.', 'Flaring elbows straight out at 90°, which grinds the shoulders.'],
    whenToUse:      'The default pressing pattern: upper-body strength plus a moving plank for trunk stiffness in one movement.',
  },
  db_press: {
    startPosition:  'Standing or half-kneeling, one dumbbell at shoulder height, wrist stacked over elbow, ribs down.',
    finishPosition: 'Arm locked out overhead with the biceps near the ear, pelvis level, trunk quiet.',
    howTo:          'Brace the trunk, press the dumbbell straight up without leaning away, then lower to the shoulder with control.',
    tips:           ['Squeeze the glute on the same side to stop the ribs flaring.', 'Half-kneeling first if the standing press arches your back.'],
    mistakes:       ['Side-bending away from the working arm to cheat the press.', 'Cutting the lockout short and letting the weight drift forward.'],
    whenToUse:      'Overhead strength with an anti-side-bend core demand — good carry-over to upright posture late in runs.',
  },
  overhead_press: {
    startPosition:  'Stand feet hip-width, dumbbells at shoulder height, forearms vertical, glutes lightly squeezed.',
    finishPosition: 'Arms locked out overhead, weights stacked over shoulders and hips, ribs down.',
    howTo:          'Brace, press both dumbbells straight overhead without arching the low back, then lower under control to the shoulders.',
    tips:           ['Squeeze the glutes throughout — it protects the lower back.', 'Exhale through the sticking point.'],
    mistakes:       ['Arching the lumbar spine to press the last few inches.', 'Pressing forward of the head instead of stacking over the shoulders.'],
    whenToUse:      'Efficient upper-body strength for hybrid athletes; pairs well with rows for shoulder balance.',
  },
  db_row: {
    startPosition:  'One hand and knee braced on a bench, flat back, dumbbell hanging under the shoulder.',
    finishPosition: 'Dumbbell at the hip/lower-rib line, elbow past the torso, shoulder blade pulled back and down.',
    howTo:          'Row the dumbbell toward the hip pocket, leading with the elbow, pause, then lower long and slow.',
    tips:           ['Think "elbow to back pocket," not "hand to chest."', 'Keep the neck long; eyes down at the bench.'],
    mistakes:       ['Shrugging the shoulder toward the ear as you pull.', 'Twisting the torso open to heave the weight up.'],
    whenToUse:      'Balances all the forward posture of running and desk life; builds the mid-back that keeps arm swing efficient.',
  },
  band_pull_apart: {
    startPosition:  'Arms straight ahead at shoulder height, light band held with hands shoulder-width.',
    finishPosition: 'Band touching the chest, arms wide, shoulder blades squeezed together without shrugging.',
    howTo:          'Pull the band apart by driving the hands out and back, pause on the chest, return with control.',
    tips:           ['Lead with the back of the hands; keep wrists neutral.', 'High reps, light band — this is postural endurance work.'],
    mistakes:       ['Shrugging into the neck.', 'Bending the elbows and turning it into a row.'],
    whenToUse:      'Cheap insurance for shoulder and posture health; ideal warm-up filler or desk-break movement.',
  },
  face_pull: {
    startPosition:  'Band anchored at face height, arms extended, palms facing each other.',
    finishPosition: 'Hands beside the ears, elbows high and wide, shoulder blades down and back.',
    howTo:          'Pull toward the bridge of the nose while externally rotating so the knuckles finish pointing up; pause, return slowly.',
    tips:           ['Finish each rep like a "double biceps" pose — that\'s the external rotation.', 'Keep the ribs down; don\'t lean back to finish reps.'],
    mistakes:       ['Pulling low toward the chest and skipping the rotation.', 'Using so much band that the shrug takes over.'],
    whenToUse:      'Rear-delt and rotator-cuff health — pairs with pressing to keep shoulders balanced.',
  },
  farmers_carry: {
    startPosition:  'Stand tall between two heavy dumbbells, grip set, shoulders packed down.',
    finishPosition: 'Same tall posture at the end of the walk — the finish position is the start position, maintained.',
    howTo:          'Deadlift the weights up, walk with short quick steps and level hips, breathe behind a braced trunk, set down with a flat back.',
    tips:           ['Pick a weight that challenges grip by the last 10 meters.', 'Eyes on the horizon; the head leads posture.'],
    mistakes:       ['Leaning back or waddling side to side under load.', 'Crashing the weights down with a rounded back at the end.'],
    whenToUse:      'Whole-body strength endurance with zero technique barrier — grip, trunk, and hips under fatigue.',
  },
  suitcase_carry: {
    startPosition:  'One heavy dumbbell at your side, opposite hand free, shoulders level.',
    finishPosition: 'Level shoulders and level pelvis maintained across the full walking distance.',
    howTo:          'Walk tall while the load tries to bend you sideways; resist with the opposite obliques and hip. Swap sides evenly.',
    tips:           ['If the free-side hip drops, the weight is too heavy.', 'Slow, deliberate steps beat fast ones.'],
    mistakes:       ['Leaning away from the weight instead of staying stacked.', 'Holding the breath the whole walk.'],
    whenToUse:      'Directly trains the lateral-hip and trunk control that prevents hip drop in single-leg stance — running-specific core work.',
  },
  dead_bug: {
    startPosition:  'On your back, hips and knees at 90°, arms pointing at the ceiling, low back gently pressed to the floor.',
    finishPosition: 'Opposite arm overhead and opposite leg extended just above the floor, low back still flat.',
    howTo:          'Exhale and reach one arm and the opposite leg away slowly; return and switch. The low back never leaves the floor.',
    tips:           ['Exhale fully as the limbs travel — it keeps the ribs down.', 'Shorten the lever (heel taps) if the back arches.'],
    mistakes:       ['Arching the low back as the leg extends.', 'Racing through reps instead of moving on the breath.'],
    whenToUse:      'The foundational anti-extension drill: teaches the trunk to stay quiet while the limbs move — exactly what running asks for.',
  },
  copenhagen_plank: {
    startPosition:  'Side plank with the top foot or knee supported on a bench, bottom leg free, elbow under shoulder.',
    finishPosition: 'Body in one straight line, hips lifted, held by the top-leg adductors.',
    howTo:          'Lift the hips until the body is straight, squeeze the top inner thigh into the bench, hold, breathe, lower with control.',
    tips:           ['Start with the knee (short lever) on the bench and progress to the foot.', 'Build from 10–15 second holds.'],
    mistakes:       ['Hips sagging toward the floor.', 'Rolling the chest toward the ceiling.'],
    whenToUse:      'The evidence-backed groin protector — adductor strength that also stabilizes the pelvis in stance.',
  },
  side_plank: {
    startPosition:  'On one elbow (under the shoulder), feet stacked or staggered, body straight from head to heels.',
    finishPosition: 'Hips lifted in line with shoulders and ankles, neck long, top hand on hip or reaching up.',
    howTo:          'Lift the hips off the floor, hold a straight line while breathing normally, then lower slowly. Match time on both sides.',
    tips:           ['Push the floor away through the forearm to keep the shoulder healthy.', 'Drop to the bottom knee to scale without changing the pattern.'],
    mistakes:       ['Hips drifting back so the body makes a banana.', 'Sagging at the waist as the set gets hard.'],
    whenToUse:      'Lateral trunk and glute-med endurance — the anti-hip-drop hold, especially useful alongside gait findings.',
  },
  bird_dog: {
    startPosition:  'Hands under shoulders, knees under hips, spine neutral, gaze at the floor.',
    finishPosition: 'One arm and the opposite leg extended level with the torso, pelvis flat as a tabletop.',
    howTo:          'Reach one arm forward and the opposite heel back until both are level, pause 2 seconds, return without shifting the hips, alternate.',
    tips:           ['Imagine balancing a glass of water on the low back.', 'Reach long, not high — height comes from hip extension, not back arch.'],
    mistakes:       ['Hiking or rotating the pelvis as the leg lifts.', 'Arching the neck to look forward.'],
    whenToUse:      'Spine-friendly trunk coordination; a staple in warm-ups and return-to-running progressions.',
  },
  plank: {
    startPosition:  'Forearms on the floor with elbows under shoulders, feet together, body lifted in one line.',
    finishPosition: 'Same line held: ears, shoulders, hips, and ankles stacked straight, abs and glutes braced.',
    howTo:          'Brace as if about to take a light punch, breathe steadily behind the brace, and hold the line without sagging or piking.',
    tips:           ['Squeeze glutes and quads — the plank is a whole-body hold.', 'Shorter perfect holds beat long saggy ones.'],
    mistakes:       ['Hips sagging as the set ends.', 'Holding the breath instead of breathing behind the brace.'],
    whenToUse:      'The baseline anti-extension hold; use it to teach bracing before loading squats and hinges.',
  },
  glute_bridge: {
    startPosition:  'On your back, knees bent, feet flat hip-width and close to the hips, arms at the sides.',
    finishPosition: 'Hips extended in a straight line from knees to shoulders, glutes squeezed, ribs down.',
    howTo:          'Drive through the heels, lift the hips to full extension, hold one full second at the top, lower with control.',
    tips:           ['Exhale at the top and tuck the pelvis slightly — no low-back finish.', 'Progress to single-leg once 15 clean reps are easy.'],
    mistakes:       ['Pushing through the toes so the hamstrings cramp.', 'Arching the back past where the hips can extend.'],
    whenToUse:      'Entry-level hip extension: wakes the glutes before runs and rebuilds the pattern after time off.',
  },
  single_leg_calf_raise: {
    startPosition:  'Ball of one foot on a step edge, heel free, fingertip on a rail for balance only.',
    finishPosition: 'Fully tall on the ball of the foot, ankle stacked straight — not rolled out.',
    howTo:          'Rise all the way up over the big-toe side, pause, then lower the heel below the step over 3 seconds for a full stretch.',
    tips:           ['The slow lower-down is where the tendon adapts — never bounce.', 'Add a dumbbell when 15 smooth reps are easy.'],
    mistakes:       ['Rolling onto the outside of the foot at the top.', 'Short pulsing reps that skip the stretched bottom position.'],
    whenToUse:      'The single most valuable ankle exercise for runners: calf strength and Achilles capacity in one.',
  },
  seated_calf_raise: {
    startPosition:  'Seated with the balls of the feet on a step and weight resting on the knees, heels down in a stretch.',
    finishPosition: 'Heels lifted as high as possible with the knees staying bent throughout.',
    howTo:          'With knees bent ~90°, raise the heels against the weight, pause at the top, lower slowly to a full stretch.',
    tips:           ['The bent knee targets the soleus — the workhorse of distance running.', 'Go heavier than feels natural; the soleus handles multiples of bodyweight.'],
    mistakes:       ['Straightening the knees, which shifts work away from the soleus.', 'Cutting the bottom stretch short.'],
    whenToUse:      'Soleus-specific loading — the muscle that absorbs the most force per stride and protects the Achilles and shin.',
  },
  pogo_hops: {
    startPosition:  'Standing tall, knees nearly straight, arms relaxed, weight on the balls of the feet.',
    finishPosition: 'Same tall position — the movement lives entirely at the ankle between hops.',
    howTo:          'Bounce off the ground using only the ankles like springs: quick, quiet contacts, minimal knee bend, tall posture.',
    tips:           ['Think "hot pavement" — minimal ground time.', 'Quiet landings mean the tendon is doing its elastic job.'],
    mistakes:       ['Bending the knees and turning hops into small squats.', 'Loud flat-footed landings.'],
    whenToUse:      'Tendon stiffness and elastic recoil — the plyometric bridge between calf strength and fast, springy running.',
  },
  box_jump: {
    startPosition:  'Athletic stance an arm\'s length from a mid-shin to knee-height box, arms back, hips loaded.',
    finishPosition: 'Standing quietly on top of the box in a quarter squat, chest up, full feet on the surface.',
    howTo:          'Swing the arms and jump onto the box, land softly in a quarter squat, stand tall, then step (never jump) back down.',
    tips:           ['Box height is about landing quality, not ego — soft and silent wins.', 'Step down every rep to spare the Achilles.'],
    mistakes:       ['Landing in a deep squat because the box is too high.', 'Rebounding off the floor between reps when fatigued.'],
    whenToUse:      'Teaches explosive hip extension and soft landings; use fresh, early in sessions, in low volumes.',
  },
  single_leg_hop: {
    startPosition:  'Standing on one leg, slight bend at hip and knee, arms ready to counterbalance.',
    finishPosition: 'Balanced landing on the same leg, quiet foot, knee tracking over the toes.',
    howTo:          'Hop forward or in place on one leg, sticking each landing for a beat before the next hop. Progress distance before speed.',
    tips:           ['Stick and hold each landing for 1–2 seconds at first.', 'Match volume on both legs and stop when landings get loud.'],
    mistakes:       ['Knee caving inward on landing.', 'Chasing distance with sloppy, noisy landings.'],
    whenToUse:      'The gold-standard return-to-running and durability test: single-leg power plus landing control.',
  },
  hip_90_90: {
    startPosition:  'Seated with the front leg bent 90° in front and the rear leg bent 90° to the side, torso tall.',
    finishPosition: 'Chest hinged forward over the front shin with a long spine, breathing into the front hip.',
    howTo:          'Keep the spine long and hinge the chest over the front shin until the outer hip stretches; hold and breathe, then switch sides.',
    tips:           ['Move with the exhale; each breath buys a little more range.', 'Lift the chest first — a rounded slump wastes the stretch.'],
    mistakes:       ['Slumping through the spine instead of hinging at the hip.', 'Forcing depth into a pinching sensation.'],
    whenToUse:      'Hip rotation mobility for stride symmetry; useful after long runs and on recovery days.',
  },
  hip_flexor_stretch: {
    startPosition:  'Half-kneeling: down-knee on a pad, front foot flat, both knees near 90°, pelvis tucked slightly.',
    finishPosition: 'Gentle stretch felt down the front of the kneeling-side hip and thigh, torso tall throughout.',
    howTo:          'Tuck the pelvis, squeeze the kneeling-side glute, and shift a few centimeters forward until the front of the hip stretches. Hold and breathe.',
    tips:           ['The tuck-and-squeeze creates the stretch — big forward lunging just arches the back.', 'Reach the same-side arm overhead to deepen it.'],
    mistakes:       ['Arching the low back and calling it hip extension.', 'Bouncing instead of holding steady.'],
    whenToUse:      'Counters sitting time and supports the hip extension range every stride needs.',
  },
  clamshell: {
    startPosition:  'Side-lying with hips and knees bent about 45 degrees, heels together, band around the knees, pelvis stacked.',
    finishPosition: 'Top knee rotated open like a clamshell, pelvis still stacked and motionless.',
    howTo:          'Keeping heels together, open the top knee against the band without rolling the pelvis back, pause, and lower slowly.',
    tips:           ['Small strict range beats big cheated range.', 'You should feel the burn in the side of the hip, not the front.'],
    mistakes:       ['Rolling the pelvis backward to fake more range.', 'Rushing reps so momentum replaces the glute med.'],
    whenToUse:      'Targeted glute-med activation — pairs with hip-drop or knee-valgus findings from the Movement Lab.',
  },
};

// Alias map: engine catalogue ids, exercise-store ids, and prototype screen ids
// all resolve to a canonical guide slug.
const EXERCISE_GUIDE_ALIASES: Record<string, string> = {
  // strengthEngine catalogue
  squat_goblet: 'goblet_squat',
  squat_bulgarian: 'bulgarian_split_squat',
  squat_box: 'box_squat',
  hinge_rdl: 'romanian_deadlift',
  hinge_single_rdl: 'single_leg_rdl',
  hinge_hip_thrust: 'hip_thrust',
  hinge_nordic: 'nordic_curl',
  lunge_reverse: 'reverse_lunge',
  lunge_lateral: 'lateral_lunge',
  lunge_step_up: 'step_up',
  push_pushup: 'push_up',
  push_db_press: 'db_press',
  pull_row: 'db_row',
  pull_band_pull: 'band_pull_apart',
  pull_facepull: 'face_pull',
  carry_farmers: 'farmers_carry',
  carry_suitcase: 'suitcase_carry',
  trunk_dead_bug: 'dead_bug',
  trunk_copenhagen: 'copenhagen_plank',
  trunk_side_plank: 'side_plank',
  trunk_bird_dog: 'bird_dog',
  calf_single_standing: 'single_leg_calf_raise',
  calf_seated: 'seated_calf_raise',
  calf_pogo: 'pogo_hops',
  plyo_box_jump: 'box_jump',
  plyo_single_hop: 'single_leg_hop',
  mobility_hip_90: 'hip_90_90',
  mobility_hip_flexor: 'hip_flexor_stretch',
  mobility_clamshell: 'clamshell',
  // exerciseStore built-ins
  b_goblet_squat: 'goblet_squat',
  b_bss: 'bulgarian_split_squat',
  b_rdl: 'romanian_deadlift',
  b_hip_thrust: 'hip_thrust',
  b_nordic_curl: 'nordic_curl',
  b_lunge: 'reverse_lunge',
  b_step_up: 'step_up',
  b_pushup: 'push_up',
  b_ohp: 'overhead_press',
  b_row: 'db_row',
  b_pull_apart: 'band_pull_apart',
  b_face_pull: 'face_pull',
  b_dead_bug: 'dead_bug',
  b_copenhagen: 'copenhagen_plank',
  b_side_plank: 'side_plank',
  b_bird_dog: 'bird_dog',
  b_plank: 'plank',
  b_slr_calf: 'single_leg_calf_raise',
  b_seated_calf: 'seated_calf_raise',
  b_box_jump: 'box_jump',
  b_suitcase_carry: 'suitcase_carry',
  b_hip_9090: 'hip_90_90',
  b_hip_flexor: 'hip_flexor_stretch',
  b_clam: 'clamshell',
  // prototype strength screen
  gs: 'goblet_squat',
  rdl: 'romanian_deadlift',
  gb: 'glute_bridge',
  pl: 'plank',
  dbr: 'db_row',
  pu: 'push_up',
  ohp: 'overhead_press',
  db2: 'dead_bug',
};

export function getExerciseGuide(exerciseId: string): ExerciseGuide | null {
  const slug = EXERCISE_GUIDE_ALIASES[exerciseId] ?? exerciseId;
  return GUIDES[slug] ?? null;
}
