// ─── Mobility Exercise & Workout Bank (Build 34, Wave 1B) ─────────────────────
//
// Content contract: docs/movement-readiness-evidence.md. Language stays inside
// the allowed set ("may affect", "may contribute to", "worth monitoring",
// "consider addressing") and never claims diagnosis, injury causation, or
// injury prevention. Coaching tone: gentle, breathe, back off if sharp pain —
// never "push through" or "no pain no gain".
//
// AI REPLACEMENT HOOK: this bank is a static seed. A future engine can
// personalize dose/selection per athlete without changing the MobilityWorkout
// / MobilityExercise shape or downstream store/UI.

import type { MobilityCategory, MobilityExercise, MobilityWorkout } from '../types/mobility';

// ─── Exercises ─────────────────────────────────────────────────────────────────

export const MOBILITY_EXERCISES: MobilityExercise[] = [
  {
    id: 'knee_to_wall_ankle_mobilization',
    name: 'Knee-to-Wall Ankle Mobilization',
    targetArea: 'Ankle · Calf',
    howTo: [
      'Face a wall in a half-kneeling position, front foot a few inches back from the wall.',
      'Keeping your front heel flat on the floor, drive your front knee forward toward the wall.',
      'Touch the wall with your knee if you can, then return to start — that is one rep.',
      'If your heel lifts before your knee reaches the wall, step the foot back slightly.',
    ],
    commonMistakes: [
      'Letting the heel lift off the ground to fake more range.',
      'Rushing the rep instead of controlling the forward glide.',
      'Turning the front foot outward to make the knee travel look bigger.',
    ],
    whatItShouldFeelLike: 'A mild stretch through the front of the ankle and calf — controlled, not painful.',
    whenToStopOrModify: 'Keep it gentle. Move only as far as your heel stays flat, and back off if you feel sharp pain.',
    linkedFinding: 'limited_ankle_dorsiflexion',
    dose: { sets: 2, reps: 10, perSide: true },
  },
  {
    id: 'calf_stretch_gastroc',
    name: 'Calf Stretch (Straight-Knee)',
    targetArea: 'Calf · Gastrocnemius',
    howTo: [
      'Stand facing a wall, hands on the wall for balance.',
      'Step one foot back, keeping that back knee straight and heel on the floor.',
      'Lean your hips forward until you feel a stretch up the back of the lower leg.',
      'Hold, breathing steadily, then switch sides.',
    ],
    commonMistakes: [
      'Letting the back heel lift off the floor.',
      'Bouncing instead of holding a steady position.',
      'Rotating the back foot inward instead of pointing it straight ahead.',
    ],
    whatItShouldFeelLike: 'A gentle, steady pull through the upper calf — comfortable enough to hold while breathing normally.',
    whenToStopOrModify: 'Ease off the lean if it feels sharp or if your knee complains. This should feel like a stretch, not a strain.',
    dose: { holdSec: 30, sets: 2, perSide: true },
  },
  {
    id: 'soleus_stretch',
    name: 'Soleus Stretch (Bent-Knee)',
    targetArea: 'Calf · Soleus',
    howTo: [
      'Same wall position as the calf stretch, but bend the back knee slightly.',
      'Keep the back heel down and shift your hips forward and down.',
      'You should feel this stretch lower, closer to the Achilles, than the straight-knee version.',
      'Hold, breathing steadily, then switch sides.',
    ],
    commonMistakes: [
      'Straightening the back knee, which shifts the stretch to the calf instead.',
      'Letting the back heel come up.',
      'Holding your breath through the hold.',
    ],
    whatItShouldFeelLike: 'A gentle stretch lower in the calf, nearer the ankle, without pinching or sharp discomfort.',
    whenToStopOrModify: 'Keep the hold light. If it becomes sharp or throbbing, come out of the stretch and shorten the hold next time.',
    dose: { holdSec: 30, sets: 2, perSide: true },
  },
  {
    id: 'hip_flexor_stretch_kneeling',
    name: 'Half-Kneeling Hip Flexor Stretch',
    targetArea: 'Hip Flexors',
    howTo: [
      'Kneel on one knee with the other foot planted in front, both knees near 90°.',
      'Tuck your tailbone slightly and gently shift your hips forward.',
      'Keep your torso tall — avoid arching your lower back to get more range.',
      'Hold, breathing steadily, then switch sides.',
    ],
    commonMistakes: [
      'Arching the lower back to force a bigger stretch.',
      'Shifting weight onto the back knee instead of driving the hips forward.',
      'Rushing the hold instead of easing in gradually.',
    ],
    whatItShouldFeelLike: 'A gentle stretch along the front of the hip and upper thigh of the back leg.',
    whenToStopOrModify: 'Back off the forward shift if you feel pinching in the front of the hip or low back discomfort — this should stay a mild, breathable stretch.',
    linkedFinding: 'limited_hip_extension',
    dose: { holdSec: 30, sets: 2, perSide: true },
  },
  {
    id: 'couch_stretch',
    name: 'Couch Stretch',
    targetArea: 'Hip Flexors · Quads',
    howTo: [
      'Kneel in front of a couch or wall, back shin resting vertically against it.',
      'Keep the front foot planted and torso upright, tucking the tailbone slightly.',
      'Gently rise the torso taller to deepen the stretch through the back leg\'s hip and thigh.',
      'Hold, breathing steadily, then switch sides.',
    ],
    commonMistakes: [
      'Going for maximum range on day one instead of easing in gradually.',
      'Letting the lower back arch to compensate.',
      'Holding tension in the shoulders instead of relaxing into the position.',
    ],
    whatItShouldFeelLike: 'A noticeable but tolerable stretch through the front of the hip and thigh — more intense than the kneeling version.',
    whenToStopOrModify: 'This is a deeper stretch than most on this list — ease in slowly, use a shallower knee bend if it feels like too much, and stop if you feel sharp or pinching pain in the knee or hip.',
    linkedFinding: 'limited_hip_extension',
    dose: { holdSec: 30, sets: 2, perSide: true },
  },
  {
    id: 'ninety_ninety_hip_switches',
    name: '90/90 Hip Switches',
    targetArea: 'Hips · Rotation',
    howTo: [
      'Sit on the floor with both knees bent near 90°, one leg in front, one to the side.',
      'Keeping your chest tall, lift both knees slightly and rotate to switch legs to the other side.',
      'Control the movement down on both sides rather than dropping into it.',
      'Continue alternating for the prescribed reps.',
    ],
    commonMistakes: [
      'Using your hands to yank the legs through instead of rotating from the hips.',
      'Letting the torso collapse forward to help the legs switch.',
      'Rushing the switch instead of controlling it in both directions.',
    ],
    whatItShouldFeelLike: 'Work through a rotational range in the hips — some effort to control, but not painful.',
    whenToStopOrModify: 'Slow down or use a hand for support if balance is hard. Stop if you feel pinching in the front of the hip.',
    dose: { sets: 2, reps: 10 },
  },
  {
    id: 'adductor_rockbacks',
    name: 'Adductor Rockbacks',
    targetArea: 'Inner Thigh · Adductors',
    howTo: [
      'Start in a wide kneeling straddle, one leg bent at 90°, the other extended out to the side.',
      'Keeping both feet flat/planted, rock your hips back toward the bent-knee heel.',
      'Feel the stretch build through the inner thigh of the extended leg, then rock forward to release.',
      'Repeat, then switch sides.',
    ],
    commonMistakes: [
      'Rounding the low back instead of hinging from the hips.',
      'Forcing the range instead of rocking gently back and forth.',
      'Letting the extended leg\'s foot roll instead of staying planted.',
    ],
    whatItShouldFeelLike: 'A building, controllable stretch through the inner thigh as you rock back — never a sharp pull.',
    whenToStopOrModify: 'Rock back only as far as feels smooth. Stop if you feel sharp groin pain and reduce the range next time.',
    dose: { sets: 2, reps: 8, perSide: true },
  },
  {
    id: 'thoracic_open_books',
    name: 'Thoracic Open Books',
    targetArea: 'Upper Back · Thoracic Spine',
    howTo: [
      'Lie on your side with knees stacked and bent, arms extended together in front of you.',
      'Keeping your bottom knee anchored, rotate your top arm and chest open toward the ceiling and floor behind you.',
      'Follow your top hand with your eyes as you rotate, then return to start.',
      'Complete the reps, then switch sides.',
    ],
    commonMistakes: [
      'Letting the hips and knees rotate along with the chest, which removes the stretch.',
      'Rushing through the range instead of rotating with control.',
      'Holding the breath through the rotation.',
    ],
    whatItShouldFeelLike: 'A mobilizing stretch through the mid-back and chest as you rotate — controlled, not forced.',
    whenToStopOrModify: 'Keep the bottom knee anchored and only rotate as far as stays comfortable. Ease off if you feel sharp pain rather than a stretch.',
    dose: { sets: 2, reps: 8, perSide: true },
  },
  {
    id: 'cat_cow',
    name: 'Cat-Cow',
    targetArea: 'Spine · Core',
    howTo: [
      'Start on hands and knees, wrists under shoulders, knees under hips.',
      'Inhale, drop your belly and lift your chest and tailbone (cow).',
      'Exhale, round your spine toward the ceiling, tucking chin and tailbone (cat).',
      'Flow slowly between the two positions with your breath.',
    ],
    commonMistakes: [
      'Moving faster than your breath instead of syncing the two.',
      'Only moving the neck instead of flowing through the whole spine.',
      'Locking the elbows instead of keeping them soft.',
    ],
    whatItShouldFeelLike: 'A gentle, easy wave through the spine — this should feel good, not effortful.',
    whenToStopOrModify: 'Keep the range small and pain-free. If any position pinches, shrink the range rather than pushing through it.',
    dose: { sets: 2, reps: 10 },
  },
  {
    id: 'childs_pose_breathing',
    name: "Child's Pose Breathing",
    targetArea: 'Low Back · Hips',
    howTo: [
      'Kneel and sit your hips back toward your heels, reaching your arms forward on the floor.',
      'Let your chest and forehead relax down.',
      'Breathe slowly and fully into your low back and sides for the prescribed time.',
      'Rise slowly when finished.',
    ],
    commonMistakes: [
      'Holding tension in the shoulders instead of relaxing them down.',
      'Taking shallow chest breaths instead of full breaths into the back.',
      'Forcing the hips all the way to the heels if that is uncomfortable on the knees.',
    ],
    whatItShouldFeelLike: 'A calm, passive stretch through the low back and hips paired with easy breathing.',
    whenToStopOrModify: 'Use a cushion under the hips or knees if this pinches. It should feel restful, not painful.',
    dose: { timeSec: 60, sets: 1 },
  },
  {
    id: 'worlds_greatest_stretch',
    name: "World's Greatest Stretch",
    targetArea: 'Full Body · Hips, Thoracic, Hamstrings',
    howTo: [
      'Step into a long lunge, both hands planted inside the front foot.',
      'Rotate your front-side elbow toward the ceiling, opening your chest.',
      'Return the hand down, then straighten the front leg to feel the hamstring, keeping hands on the floor.',
      'Bend the knee back into the lunge and repeat, then switch sides.',
    ],
    commonMistakes: [
      'Letting the front knee collapse inward during the lunge.',
      'Rushing through the sequence instead of pausing briefly in each position.',
      'Forcing the rotation instead of moving within a comfortable range.',
    ],
    whatItShouldFeelLike: 'A moving stretch through the hip, chest, and hamstring of the front leg — dynamic and flowing, not held tension.',
    whenToStopOrModify: 'Use a shorter stance or drop the back knee to the floor if balance is hard. Stay within a pain-free range throughout.',
    dose: { sets: 2, reps: 5, perSide: true },
  },
  {
    id: 'ankle_rocks',
    name: 'Ankle Rocks',
    targetArea: 'Ankle',
    howTo: [
      'Stand tall, feet hip-width apart, hands on hips or a wall for balance.',
      'Rock your weight forward over your toes, letting your ankles bend, heels staying down.',
      'Rock back slightly onto your heels, then forward again.',
      'Keep the motion smooth and continuous for the prescribed reps.',
    ],
    commonMistakes: [
      'Letting the heels lift during the forward rock.',
      'Bending at the hips instead of driving the motion through the ankles.',
      'Rocking too fast to control the position.',
    ],
    whatItShouldFeelLike: 'A light, rhythmic loading through the ankles — easy and warm, not a deep stretch.',
    whenToStopOrModify: 'Use a wall for balance if needed. Shorten the range if you feel any sharp pinch at the front of the ankle.',
    dose: { sets: 2, reps: 12, perSide: false },
  },
  {
    id: 'lunge_with_rotation',
    name: 'Lunge with Rotation',
    targetArea: 'Hips · Thoracic Spine',
    howTo: [
      'Step into a forward lunge, both knees near 90°.',
      'Rotate your torso and both arms toward the front-leg side.',
      'Rotate back to center, then push back to standing.',
      'Repeat, alternating legs or completing one side at a time as prescribed.',
    ],
    commonMistakes: [
      'Rotating from the low back instead of the mid-back and hips together.',
      'Letting the front knee drift past the toes or collapse inward.',
      'Losing balance by rotating too far, too fast.',
    ],
    whatItShouldFeelLike: 'A dynamic, warming stretch through the hip and trunk — controlled effort, not strain.',
    whenToStopOrModify: 'Shorten the lunge depth or rotation range if balance or comfort is an issue. Keep it smooth and pain-free.',
    dose: { sets: 2, reps: 8, perSide: true },
  },
  {
    id: 'hamstring_flossing',
    name: 'Hamstring Flossing',
    targetArea: 'Hamstrings · Nerve Glide',
    howTo: [
      'Stand tall, or hinge slightly at the hips, one heel propped in front on a low surface (or lifted, knee straight).',
      'Keep a slight bend in your standing knee and hinge your hips forward gently, then return upright.',
      'Move in and out of the position smoothly rather than holding a static stretch.',
      'Repeat, then switch legs.',
    ],
    commonMistakes: [
      'Rounding the back to force more range at the hamstring.',
      'Locking the front knee hard, which can feel pinching rather than stretching.',
      'Moving too fast to control the hinge.',
    ],
    whatItShouldFeelLike: 'A mild, moving tension behind the thigh that eases as you move — not a held, intense stretch.',
    whenToStopOrModify: 'Keep the range small if you feel any sharp or nerve-like tingling, and ease back into a smaller motion.',
    dose: { sets: 2, reps: 10, perSide: true },
  },
  {
    id: 'glute_bridge',
    name: 'Glute Bridge',
    targetArea: 'Glutes · Hip Extension',
    howTo: [
      'Lie on your back, knees bent, feet flat about hip-width apart.',
      'Squeeze your glutes and press through your heels to lift your hips until your body forms a straight line from knees to shoulders.',
      'Pause briefly at the top, then lower with control.',
      'Repeat for the prescribed reps.',
    ],
    commonMistakes: [
      'Overarching the low back at the top instead of squeezing the glutes.',
      'Pushing through the toes instead of the heels.',
      'Dropping quickly instead of lowering under control.',
    ],
    whatItShouldFeelLike: 'Working effort in the glutes and hamstrings at the top of the movement — not your low back.',
    whenToStopOrModify: 'Reduce the range or the number of reps if your low back takes over the effort. This is loaded control work, not a stretch — some muscular fatigue is expected.',
    dose: { sets: 3, reps: 12 },
  },
  {
    id: 'controlled_hip_cars',
    name: 'Controlled Hip CARs',
    targetArea: 'Hip Joint · Rotational Control',
    howTo: [
      'Stand tall holding a wall or sturdy surface for balance.',
      'Lift one knee up, then rotate it out to the side, then reach it back behind you, keeping the motion slow and controlled.',
      'Trace the largest smooth circle you can control without shifting your trunk.',
      'Complete the reps, then switch directions or legs as prescribed.',
    ],
    commonMistakes: [
      'Letting the torso lean or twist to fake extra hip range.',
      'Moving fast through the circle instead of staying slow and controlled.',
      'Holding the breath through the movement.',
    ],
    whatItShouldFeelLike: 'Controlled effort through a full circle at the hip — like actively "owning" the range, not passively stretching into it.',
    whenToStopOrModify: 'Shrink the circle if you can\'t keep the trunk still, and stop if you feel pinching at the front or back of the hip.',
    dose: { sets: 2, reps: 5, perSide: true },
  },
  {
    id: 'squat_pry',
    name: 'Squat Pry',
    targetArea: 'Ankles · Hips · Groin',
    howTo: [
      'Lower into the deepest comfortable squat, feet flat, holding onto something for balance if needed.',
      'Rest your elbows against the inside of your knees.',
      'Gently pry your knees outward using your elbows, rocking side to side.',
      'Hold the general position for the prescribed time, moving gently within it.',
    ],
    commonMistakes: [
      'Letting the heels lift to fake a deeper squat.',
      'Forcing the knees open aggressively instead of prying gently.',
      'Rounding the low back heavily instead of keeping the chest reasonably tall.',
    ],
    whatItShouldFeelLike: 'A full-range stretch through the ankles, hips, and inner thighs while your muscles work to hold the position.',
    whenToStopOrModify: 'Elevate your heels on a rolled towel if you can\'t keep them flat. Stop prying if you feel sharp joint pain.',
    dose: { timeSec: 30, sets: 2 },
  },
  {
    id: 'single_leg_heel_raise',
    name: 'Single-Leg Heel Raise (Capacity Drill)',
    targetArea: 'Calf · Soleus Capacity',
    howTo: [
      'Stand on one leg, holding a wall or rail for light balance support.',
      'Rise onto the ball of your foot as high as you can, then lower with control.',
      'Keep your knee mostly straight and your weight centered over the big toe.',
      'Repeat for the prescribed reps, then switch legs.',
    ],
    commonMistakes: [
      'Using the support hand to pull yourself up instead of pushing through the calf.',
      'Dropping quickly instead of lowering under control.',
      'Letting the ankle roll outward or inward through the movement.',
    ],
    whatItShouldFeelLike: 'Building muscular fatigue in the calf as reps accumulate — this is a capacity drill, so working effort is expected.',
    whenToStopOrModify: 'Stop the set if you feel sharp Achilles or calf pain (distinct from normal working fatigue), and use two hands on support for balance if needed.',
    linkedFinding: 'calf_capacity',
    dose: { sets: 3, reps: 15, perSide: true },
  },
  {
    id: 'standing_quad_stretch',
    name: 'Standing Quad Stretch',
    targetArea: 'Quads · Hip Flexors',
    howTo: [
      'Stand tall, holding onto a wall or chair for balance if needed.',
      'Bend one knee and grab that foot or ankle behind you, keeping knees close together.',
      'Gently pull the heel toward your glute until you feel a stretch through the front of the thigh.',
      'Hold, breathing steadily, then switch sides.',
    ],
    commonMistakes: [
      'Letting the bent knee drift out to the side instead of staying in line with the standing leg.',
      'Arching the low back to force more range.',
      'Yanking the ankle instead of easing into the stretch.',
    ],
    whatItShouldFeelLike: 'A steady stretch through the front of the thigh — comfortable enough to hold while breathing normally.',
    whenToStopOrModify: 'Hold a wall for balance if needed, and ease off if you feel pinching in the knee rather than a stretch in the thigh.',
    dose: { holdSec: 30, sets: 2, perSide: true },
  },
  {
    id: 'seated_spinal_twist',
    name: 'Seated Spinal Twist',
    targetArea: 'Spine · Obliques',
    howTo: [
      'Sit tall on the floor or a chair with both feet planted.',
      'Place one hand behind you and the other on the opposite knee.',
      'Gently rotate your torso toward the back hand, leading with your chest, not just your head.',
      'Hold, breathing steadily, then switch sides.',
    ],
    commonMistakes: [
      'Rounding forward instead of staying tall through the rotation.',
      'Forcing the twist with the arms instead of rotating from the trunk.',
      'Holding the breath through the hold.',
    ],
    whatItShouldFeelLike: 'A gentle wringing sensation through the mid-back and sides — controlled, not forced.',
    whenToStopOrModify: 'Rotate only as far as feels smooth. Ease off if you feel sharp pain rather than a stretch.',
    dose: { holdSec: 20, sets: 2, perSide: true },
  },
  {
    id: 'shoulder_wall_slides',
    name: 'Shoulder Wall Slides',
    targetArea: 'Shoulders · Upper Back',
    howTo: [
      'Stand with your back, head, and arms against a wall, elbows and wrists touching the wall at about shoulder height.',
      'Slide your arms upward along the wall as far as you can while keeping contact, then slide back down.',
      'Keep your low back gently flat against the wall throughout, not arched.',
      'Repeat for the prescribed reps.',
    ],
    commonMistakes: [
      'Letting the arms or low back come off the wall to fake more range.',
      'Shrugging the shoulders up toward the ears instead of sliding smoothly.',
      'Rushing the reps instead of controlling the slide in both directions.',
    ],
    whatItShouldFeelLike: 'Working effort through the upper back and shoulders as you slide, with a mild stretch across the chest at the top.',
    whenToStopOrModify: 'Shorten the range if you cannot keep your arms and back on the wall, and stop if you feel shoulder pinching rather than working effort.',
    dose: { sets: 2, reps: 10 },
  },
  {
    id: 'standing_it_band_stretch',
    name: 'Standing IT Band Stretch',
    targetArea: 'Outer Hip · IT Band',
    howTo: [
      'Stand tall next to a wall for balance, feet together.',
      'Cross the outside leg behind the inside leg, then shift your hips sideways away from that leg.',
      'Reach the same-side arm overhead and lean gently toward the crossed side.',
      'Hold, breathing steadily, then switch sides.',
    ],
    commonMistakes: [
      'Leaning the torso forward instead of sideways.',
      'Forcing the hip shift instead of easing into it.',
      'Losing balance by skipping the wall support.',
    ],
    whatItShouldFeelLike: 'A stretch along the outside of the hip and thigh — mild to moderate, never sharp.',
    whenToStopOrModify: 'Use the wall for balance and shorten the side-shift if you feel pinching at the hip or knee instead of a stretch.',
    dose: { holdSec: 25, sets: 2, perSide: true },
  },
  {
    id: 'figure_four_glute_stretch',
    name: 'Figure-Four Glute Stretch',
    targetArea: 'Glutes · Outer Hip',
    howTo: [
      'Lie on your back with knees bent, feet flat on the floor.',
      'Cross one ankle over the opposite knee, forming a "four" shape.',
      'Reach through and gently pull the uncrossed thigh toward your chest until you feel a stretch in the crossed leg\'s glute.',
      'Hold, breathing steadily, then switch sides.',
    ],
    commonMistakes: [
      'Pulling hard and fast instead of easing in gradually.',
      'Letting the crossed-leg knee collapse inward instead of staying open.',
      'Lifting the head and shoulders instead of staying relaxed on the floor.',
    ],
    whatItShouldFeelLike: 'A deep, steady stretch through the glute and outer hip of the crossed leg.',
    whenToStopOrModify: 'Pull only as far as feels like a stretch, not a pinch, and support your head with a pillow if that is more comfortable.',
    dose: { holdSec: 30, sets: 2, perSide: true },
  },
  {
    id: 'ankle_alphabet',
    name: 'Ankle Alphabet',
    targetArea: 'Ankle',
    howTo: [
      'Sit or lie down with one leg extended, ankle relaxed and off the floor.',
      'Using only your ankle and foot, "write" the letters of the alphabet in the air, keeping the motion slow.',
      'Complete as much of the alphabet as prescribed, then switch feet.',
      'Keep the rest of the leg still — the movement comes from the ankle.',
    ],
    commonMistakes: [
      'Moving the whole leg instead of isolating the ankle.',
      'Rushing through the letters instead of tracing them fully.',
      'Skipping letters that feel stiff instead of moving through them gently.',
    ],
    whatItShouldFeelLike: 'A light, exploratory movement through the full range of the ankle — easy, not effortful.',
    whenToStopOrModify: 'Shorten to a partial alphabet if needed, and ease off any direction that feels sharp rather than simply stiff.',
    dose: { timeSec: 45, sets: 1, perSide: true },
  },
];

export function getMobilityExercise(id: string): MobilityExercise | undefined {
  return MOBILITY_EXERCISES.find(e => e.id === id);
}

// ─── Workouts ──────────────────────────────────────────────────────────────────

export const MOBILITY_WORKOUTS: MobilityWorkout[] = [
  {
    id: 'pre_run_mobility_primer',
    title: 'Pre-Run Mobility Primer',
    purpose: 'A short dynamic warm-up to get your ankles, hips, and spine moving before you run.',
    category: 'pre_run',
    categories: ['pre_run', 'full_body', 'running_readiness', 'walking_readiness'],
    targetAreas: ['Ankles', 'Hips', 'Spine'],
    recommendedFrequency: 'Before every run',
    durationMin: 8,
    evidenceRationale: 'Dynamic mobility increases range of motion without the transient force loss that long static holds can cause right before intense effort, so primers use movement rather than held stretches.',
    exercises: [
      { exerciseId: 'ankle_rocks', cues: ['Keep heels down', 'Smooth, rhythmic motion'] },
      { exerciseId: 'cat_cow', cues: ['Move with your breath'] },
      { exerciseId: 'worlds_greatest_stretch', cues: ['Pause briefly in each position, don\'t rush'] },
      { exerciseId: 'lunge_with_rotation', cues: ['Rotate from the trunk, not just the arms'] },
      { exerciseId: 'controlled_hip_cars', dose: { reps: 4 }, cues: ['Keep the trunk still, move the hip'] },
      { exerciseId: 'glute_bridge', dose: { sets: 1, reps: 10 }, cues: ['Quick activation set — squeeze at the top'] },
    ],
  },
  {
    id: 'post_run_recovery_mobility',
    title: 'Post-Run Recovery Mobility',
    purpose: 'Static stretches and easy breathing to help your body settle after a run.',
    category: 'post_run',
    categories: ['post_run', 'full_body'],
    targetAreas: ['Calves', 'Hips', 'Low Back'],
    recommendedFrequency: 'After harder or longer runs',
    durationMin: 12,
    evidenceRationale: 'Static stretching reliably improves joint range of motion; used after training rather than immediately before, it carries no meaningful performance downside.',
    exercises: [
      { exerciseId: 'calf_stretch_gastroc', cues: ['Heel stays down'] },
      { exerciseId: 'soleus_stretch', cues: ['Bend the back knee slightly'] },
      { exerciseId: 'hip_flexor_stretch_kneeling', cues: ['Tuck the tailbone before shifting forward'] },
      { exerciseId: 'hamstring_flossing', cues: ['Small, smooth range — not a deep hold'] },
      { exerciseId: 'childs_pose_breathing', cues: ['Slow, full breaths'] },
    ],
  },
  {
    id: 'ankle_dorsiflexion_routine',
    title: 'Ankle Dorsiflexion Routine',
    purpose: 'Targeted work to improve how far your ankle bends forward, which supports squat depth and landing mechanics.',
    category: 'ankle',
    categories: ['ankle', 'lower_body', 'running_readiness', 'walking_readiness'],
    targetAreas: ['Ankle', 'Calf'],
    recommendedFrequency: '3x/week',
    durationMin: 10,
    evidenceRationale: 'Limited ankle mobility may affect squat depth and landing mechanics, and ankle range of motion is trainable with consistent mobility work.',
    linkedAssessmentFinding: 'limited_ankle_dorsiflexion',
    exercises: [
      { exerciseId: 'knee_to_wall_ankle_mobilization', cues: ['Heel flat, knee travels forward'] },
      { exerciseId: 'ankle_rocks', cues: ['Warm the joint up first'] },
      { exerciseId: 'calf_stretch_gastroc', cues: ['Steady hold, breathe through it'] },
      { exerciseId: 'soleus_stretch', cues: ['Lower stretch, bent knee'] },
      { exerciseId: 'single_leg_heel_raise', dose: { sets: 2, reps: 12 }, cues: ['Full range, controlled tempo'] },
    ],
  },
  {
    id: 'hip_extension_mobility',
    title: 'Hip Extension Mobility',
    purpose: 'Opens up the front of the hip so your leg can extend further behind you during the running stride.',
    category: 'hip',
    categories: ['hip', 'lower_body', 'running_readiness'],
    targetAreas: ['Hip Flexors', 'Quads'],
    recommendedFrequency: '3x/week',
    durationMin: 12,
    evidenceRationale: 'Limited hip extension may affect stride mechanics behind the body, and hip extension range of motion improves with consistent stretching and strengthening work.',
    linkedAssessmentFinding: 'limited_hip_extension',
    exercises: [
      { exerciseId: 'hip_flexor_stretch_kneeling', cues: ['Torso tall, no low-back arch'] },
      { exerciseId: 'couch_stretch', cues: ['Ease in gradually — this one is more intense'] },
      { exerciseId: 'ninety_ninety_hip_switches', cues: ['Rotate from the hips, not the hands'] },
      { exerciseId: 'controlled_hip_cars', cues: ['Slow circles, full control'] },
    ],
  },
  {
    id: 'hip_control_and_mobility',
    title: 'Hip Control + Mobility',
    purpose: 'Combines hip range of motion with loaded control work to support balance and trunk position while running.',
    category: 'hip',
    categories: ['hip', 'problem_areas', 'lower_body'],
    targetAreas: ['Hips', 'Glutes', 'Trunk'],
    recommendedFrequency: '2–3x/week',
    durationMin: 12,
    evidenceRationale: 'Trunk and pelvic control observations are associative rather than causal, so this pairs mobility with hip/glute strengthening — the modality with the strongest evidence for supporting movement quality.',
    linkedAssessmentFinding: 'trunk_pelvic_control',
    exercises: [
      { exerciseId: 'ninety_ninety_hip_switches', cues: ['Control both directions'] },
      { exerciseId: 'glute_bridge', cues: ['Squeeze glutes at the top, not the low back'] },
      { exerciseId: 'controlled_hip_cars', cues: ['Keep the trunk quiet'] },
      { exerciseId: 'squat_pry', cues: ['Gentle pry, don\'t force it'] },
    ],
  },
  {
    id: 'low_back_mobility_reset',
    title: 'Low Back Mobility Reset',
    purpose: 'Gentle spinal movement and breathing to ease stiffness through the low back.',
    category: 'back_spine',
    categories: ['back_spine', 'problem_areas', 'full_body'],
    targetAreas: ['Low Back', 'Hips'],
    recommendedFrequency: 'As needed, up to daily',
    durationMin: 10,
    evidenceRationale: 'Dynamic mobility and breathing-paired positions increase comfort and range without the injury-prevention claims that stretching alone cannot support.',
    exercises: [
      { exerciseId: 'cat_cow', cues: ['Small, pain-free range'] },
      { exerciseId: 'childs_pose_breathing', dose: { timeSec: 90 }, cues: ['Let the breath do the work'] },
      { exerciseId: 'adductor_rockbacks', cues: ['Hinge from the hips, not the back'] },
      { exerciseId: 'thoracic_open_books', cues: ['Anchor the bottom knee'] },
    ],
  },
  {
    id: 'thoracic_mobility_for_running_posture',
    title: 'Thoracic Mobility for Running Posture',
    purpose: 'Improves rotation and extension through the upper back to support a tall, relaxed running posture.',
    category: 'upper_body',
    categories: ['upper_body', 'back_spine', 'full_body'],
    targetAreas: ['Upper Back', 'Chest'],
    recommendedFrequency: '2–3x/week',
    durationMin: 8,
    evidenceRationale: 'Dynamic thoracic mobility acutely increases range of motion without a performance cost, supporting a taller trunk position during running.',
    exercises: [
      { exerciseId: 'thoracic_open_books', cues: ['Follow your hand with your eyes'] },
      { exerciseId: 'cat_cow', cues: ['Move through the whole spine'] },
      { exerciseId: 'worlds_greatest_stretch', cues: ['Open the chest fully on the rotation'] },
    ],
  },
  {
    id: 'full_body_runner_mobility',
    title: 'Full-Body Runner Mobility',
    purpose: 'A well-rounded session touching the areas that matter most for running comfort — ankles, hips, spine, and calves.',
    category: 'full_body',
    categories: ['full_body', 'running_readiness', 'walking_readiness'],
    targetAreas: ['Ankles', 'Hips', 'Upper Back', 'Calves'],
    recommendedFrequency: '2x/week',
    durationMin: 15,
    evidenceRationale: 'Combining dynamic and static mobility with loaded control work reflects the full range of evidence-supported approaches rather than relying on stretching alone.',
    exercises: [
      { exerciseId: 'worlds_greatest_stretch', cues: ['Flow through each position'] },
      { exerciseId: 'ninety_ninety_hip_switches', cues: ['Control the switch'] },
      { exerciseId: 'thoracic_open_books', cues: ['Rotate, don\'t force'] },
      { exerciseId: 'calf_stretch_gastroc', cues: ['Steady hold'] },
      { exerciseId: 'glute_bridge', cues: ['Full squeeze at the top'] },
    ],
  },
  {
    id: 'calf_soleus_mobility_and_capacity',
    title: 'Calf/Soleus Mobility + Capacity',
    purpose: 'Combines calf and soleus stretching with loaded heel-raise work to build both range and strength.',
    category: 'lower_body',
    categories: ['lower_body', 'ankle', 'running_readiness'],
    targetAreas: ['Calf', 'Soleus', 'Achilles'],
    recommendedFrequency: '2–3x/week',
    durationMin: 12,
    evidenceRationale: 'The soleus experiences among the highest forces of any muscle during running, and calf strengthening is a cornerstone of clinical guidance for calf and Achilles capacity, so this pairs stretching with loaded reps rather than stretching alone.',
    cautionNote: 'If you have current Achilles or calf pain, ease into the heel raises and consider checking with a clinician before adding load.',
    linkedAssessmentFinding: 'calf_capacity',
    exercises: [
      { exerciseId: 'calf_stretch_gastroc', cues: ['Steady hold, both sides'] },
      { exerciseId: 'soleus_stretch', cues: ['Bent-knee version'] },
      { exerciseId: 'ankle_rocks', cues: ['Warm up the joint first'] },
      { exerciseId: 'single_leg_heel_raise', cues: ['Full range, controlled down phase'] },
    ],
  },
  {
    id: 'single_leg_control_prep',
    title: 'Single-Leg Control Prep',
    purpose: 'Builds single-leg strength and balance to support the control your body needs each time a foot hits the ground while running.',
    category: 'lower_body',
    categories: ['lower_body', 'problem_areas', 'running_readiness'],
    targetAreas: ['Hips', 'Calves', 'Balance'],
    recommendedFrequency: '2x/week',
    durationMin: 12,
    evidenceRationale: 'Single-leg strength and control work is low-risk and improves movement-quality measures, even though its link to injury outcomes is only observational.',
    linkedAssessmentFinding: 'reduced_single_leg_control',
    exercises: [
      { exerciseId: 'single_leg_heel_raise', cues: ['Balance first, height second'] },
      { exerciseId: 'glute_bridge', cues: ['Even hips, no rotation'] },
      { exerciseId: 'controlled_hip_cars', cues: ['Slow and controlled, not fast'] },
      { exerciseId: 'squat_pry', dose: { timeSec: 20 }, cues: ['Hold a stable, comfortable depth'] },
    ],
  },

  // ─── Build 36 expansion: 10 → 50 workouts. Existing ids above are untouched
  // (readiness recommendations reference them). All copy below stays inside
  // the evidence-safe claim ceiling — no diagnosis, no injury-causation or
  // injury-prevention claims. ────────────────────────────────────────────────

  // Pre-run
  {
    id: 'pre_run_ankle_activation',
    title: 'Pre-Run Ankle Activation',
    purpose: 'A quick ankle-focused warm-up to get the lower leg ready for push-off before you run.',
    category: 'pre_run',
    categories: ['pre_run', 'ankle', 'running_readiness'],
    targetAreas: ['Ankle', 'Calf'],
    recommendedFrequency: 'Before every run',
    durationMin: 5,
    evidenceRationale: 'Dynamic ankle movement increases range of motion and warms the tissue without the transient force loss static holds can cause right before effort.',
    exercises: [
      { exerciseId: 'ankle_rocks', cues: ['Smooth, continuous motion'] },
      { exerciseId: 'ankle_alphabet', dose: { timeSec: 20 }, cues: ['Keep it light and easy'] },
      { exerciseId: 'squat_pry', dose: { timeSec: 15, sets: 1 }, cues: ['Just enough to feel the ankles open up'] },
    ],
  },
  {
    id: 'pre_run_hip_opener',
    title: 'Pre-Run Hip Opener',
    purpose: 'Dynamic hip movement to prepare stride length and rotation before running.',
    category: 'pre_run',
    categories: ['pre_run', 'hip', 'running_readiness'],
    targetAreas: ['Hips'],
    recommendedFrequency: 'Before every run',
    durationMin: 6,
    evidenceRationale: 'Dynamic hip mobility acutely increases usable range of motion without the pre-effort force reduction associated with long static holds.',
    exercises: [
      { exerciseId: 'lunge_with_rotation', cues: ['Rotate from the trunk'] },
      { exerciseId: 'controlled_hip_cars', dose: { reps: 4 }, cues: ['Slow, controlled circles'] },
      { exerciseId: 'ninety_ninety_hip_switches', dose: { reps: 6 }, cues: ['Control both directions'] },
    ],
  },
  {
    id: 'pre_run_five_minute_primer',
    title: '5-Minute Pre-Run Primer',
    purpose: 'A minimal, time-crunched dynamic warm-up covering the essentials before a run.',
    category: 'pre_run',
    categories: ['pre_run', 'full_body', 'running_readiness', 'walking_readiness'],
    targetAreas: ['Ankles', 'Hips'],
    recommendedFrequency: 'Before every run',
    durationMin: 5,
    evidenceRationale: 'A short dynamic sequence increases readiness without adding meaningful time or fatigue before training.',
    exercises: [
      { exerciseId: 'ankle_rocks', cues: ['Warm the ankles first'] },
      { exerciseId: 'worlds_greatest_stretch', dose: { reps: 3 }, cues: ['Flow through smoothly'] },
      { exerciseId: 'glute_bridge', dose: { sets: 1, reps: 8 }, cues: ['Quick activation'] },
    ],
  },

  // Post-run
  {
    id: 'post_run_calf_focus',
    title: 'Post-Run Calf & Ankle Cooldown',
    purpose: 'Static calf and ankle stretching to support comfort after running.',
    category: 'post_run',
    categories: ['post_run', 'ankle', 'lower_body'],
    targetAreas: ['Calf', 'Ankle'],
    recommendedFrequency: 'After runs, especially harder efforts',
    durationMin: 8,
    evidenceRationale: 'Static stretching after training reliably improves range of motion with none of the pre-effort force concerns.',
    exercises: [
      { exerciseId: 'calf_stretch_gastroc', cues: ['Steady hold'] },
      { exerciseId: 'soleus_stretch', cues: ['Bent-knee version'] },
      { exerciseId: 'ankle_alphabet', dose: { timeSec: 30 }, cues: ['Easy, exploratory movement'] },
    ],
  },
  {
    id: 'post_run_hip_low_back',
    title: 'Post-Run Hip & Low Back Release',
    purpose: 'Gentle stretching to ease hip and low back tightness after a run.',
    category: 'post_run',
    categories: ['post_run', 'hip', 'back_spine'],
    targetAreas: ['Hips', 'Low Back'],
    recommendedFrequency: 'After longer or harder runs',
    durationMin: 10,
    evidenceRationale: 'Post-training static stretching supports comfort and range of motion in the hips and low back without the pre-effort tradeoffs of long holds.',
    exercises: [
      { exerciseId: 'hip_flexor_stretch_kneeling', cues: ['Torso tall'] },
      { exerciseId: 'figure_four_glute_stretch', cues: ['Relax into the floor'] },
      { exerciseId: 'childs_pose_breathing', cues: ['Slow, full breaths'] },
    ],
  },
  {
    id: 'post_run_full_body_cooldown',
    title: 'Full-Body Post-Run Cooldown',
    purpose: 'A well-rounded static stretch sequence touching the areas that tend to tighten up after running.',
    category: 'post_run',
    categories: ['post_run', 'full_body'],
    targetAreas: ['Calves', 'Hips', 'Hamstrings', 'Upper Back'],
    recommendedFrequency: 'After runs',
    durationMin: 12,
    evidenceRationale: 'A broad static-stretch sequence after training supports range of motion across the areas most loaded by running.',
    exercises: [
      { exerciseId: 'calf_stretch_gastroc', cues: ['Steady hold'] },
      { exerciseId: 'hamstring_flossing', cues: ['Small, smooth range'] },
      { exerciseId: 'hip_flexor_stretch_kneeling', cues: ['No low-back arch'] },
      { exerciseId: 'thoracic_open_books', cues: ['Follow your hand with your eyes'] },
    ],
  },

  // Ankle
  {
    id: 'ankle_dorsiflexion_progression',
    title: 'Ankle Dorsiflexion Progression',
    purpose: 'A progressive sequence to build on basic ankle range work for those with limited dorsiflexion.',
    category: 'ankle',
    categories: ['ankle', 'lower_body', 'running_readiness'],
    targetAreas: ['Ankle', 'Calf'],
    recommendedFrequency: '3–4x/week',
    durationMin: 10,
    evidenceRationale: 'Consistent, progressive ankle mobility work is trainable and may affect squat depth and landing mechanics.',
    linkedAssessmentFinding: 'limited_ankle_dorsiflexion',
    exercises: [
      { exerciseId: 'knee_to_wall_ankle_mobilization', dose: { sets: 3, reps: 10 }, cues: ['Track incremental progress each session'] },
      { exerciseId: 'squat_pry', cues: ['Hold the deepest comfortable position'] },
      { exerciseId: 'calf_stretch_gastroc', cues: ['Full stretch, steady hold'] },
    ],
  },
  {
    id: 'calf_capacity_builder',
    title: 'Calf Capacity Builder',
    purpose: 'Loaded heel-raise work to build calf and soleus capacity for running.',
    category: 'ankle',
    categories: ['ankle', 'lower_body', 'running_readiness'],
    targetAreas: ['Calf', 'Soleus', 'Achilles'],
    recommendedFrequency: '2–3x/week',
    durationMin: 10,
    evidenceRationale: 'The soleus experiences among the highest forces of any muscle during running, and progressive calf loading is a cornerstone of clinical guidance for calf and Achilles capacity.',
    cautionNote: 'If you have current Achilles or calf pain, ease into this and consider checking with a clinician before adding load.',
    linkedAssessmentFinding: 'calf_capacity',
    exercises: [
      { exerciseId: 'single_leg_heel_raise', dose: { sets: 4, reps: 15 }, cues: ['Full range, controlled tempo'] },
      { exerciseId: 'soleus_stretch', cues: ['Bent-knee stretch after loading'] },
    ],
  },
  {
    id: 'ankle_circles_and_control',
    title: 'Ankle Circles & Control',
    purpose: 'Active range-of-motion work to build usable ankle mobility, not just passive flexibility.',
    category: 'ankle',
    categories: ['ankle', 'lower_body'],
    targetAreas: ['Ankle'],
    recommendedFrequency: '3x/week',
    durationMin: 6,
    evidenceRationale: 'Active range-of-motion work builds the controlled, usable half of mobility that passive stretching alone does not address.',
    exercises: [
      { exerciseId: 'ankle_alphabet', dose: { timeSec: 45 }, cues: ['Full range, slow and controlled'] },
      { exerciseId: 'ankle_rocks', dose: { reps: 15 }, cues: ['Smooth, rhythmic loading'] },
    ],
  },
  {
    id: 'combined_ankle_calf_reset',
    title: 'Combined Ankle + Calf Reset',
    purpose: 'Pairs ankle mobility with calf and soleus stretching for a complete lower-leg session.',
    category: 'ankle',
    categories: ['ankle', 'lower_body', 'walking_readiness'],
    targetAreas: ['Ankle', 'Calf'],
    recommendedFrequency: '2–3x/week',
    durationMin: 10,
    evidenceRationale: 'Combining active ankle range work with static calf stretching addresses both the joint and the muscle-tendon unit that limit dorsiflexion.',
    exercises: [
      { exerciseId: 'ankle_rocks', cues: ['Warm up first'] },
      { exerciseId: 'knee_to_wall_ankle_mobilization', cues: ['Heel flat throughout'] },
      { exerciseId: 'calf_stretch_gastroc', cues: ['Steady hold'] },
      { exerciseId: 'soleus_stretch', cues: ['Bent-knee version'] },
    ],
  },

  // Hip
  {
    id: 'hip_flexor_focus',
    title: 'Hip Flexor Focus',
    purpose: 'Concentrated stretching to address tightness through the front of the hip.',
    category: 'hip',
    categories: ['hip', 'lower_body', 'running_readiness'],
    targetAreas: ['Hip Flexors'],
    recommendedFrequency: '3x/week',
    durationMin: 10,
    evidenceRationale: 'Limited hip extension may affect stride mechanics behind the body, and consistent stretching supports range of motion over time.',
    linkedAssessmentFinding: 'limited_hip_extension',
    exercises: [
      { exerciseId: 'hip_flexor_stretch_kneeling', dose: { sets: 3 }, cues: ['Torso tall throughout'] },
      { exerciseId: 'couch_stretch', cues: ['Ease in gradually'] },
      { exerciseId: 'standing_quad_stretch', cues: ['Keep knees close together'] },
    ],
  },
  {
    id: 'hip_rotation_and_control',
    title: 'Hip Rotation & Control',
    purpose: 'Active rotational work to build usable hip range for the demands of running.',
    category: 'hip',
    categories: ['hip', 'lower_body'],
    targetAreas: ['Hips'],
    recommendedFrequency: '2–3x/week',
    durationMin: 10,
    evidenceRationale: 'Active rotational control work builds the "usable" half of hip mobility that passive stretching alone does not address.',
    exercises: [
      { exerciseId: 'ninety_ninety_hip_switches', dose: { reps: 12 }, cues: ['Control the switch in both directions'] },
      { exerciseId: 'controlled_hip_cars', cues: ['Full, smooth circles'] },
      { exerciseId: 'lunge_with_rotation', cues: ['Rotate from the trunk and hips together'] },
    ],
  },
  {
    id: 'glute_activation_and_hip_control',
    title: 'Glute Activation + Hip Control',
    purpose: 'Loaded glute and hip work to support control and power through the running stride.',
    category: 'hip',
    categories: ['hip', 'lower_body', 'problem_areas'],
    targetAreas: ['Glutes', 'Hips'],
    recommendedFrequency: '2–3x/week',
    durationMin: 10,
    evidenceRationale: 'Hip and glute strengthening is the modality with the strongest evidence for supporting movement quality, ahead of stretching alone.',
    exercises: [
      { exerciseId: 'glute_bridge', dose: { sets: 3, reps: 15 }, cues: ['Squeeze at the top, not the low back'] },
      { exerciseId: 'controlled_hip_cars', cues: ['Keep the trunk quiet'] },
      { exerciseId: 'figure_four_glute_stretch', cues: ['Relax into the stretch after loading'] },
    ],
  },
  {
    id: 'outer_hip_and_it_band_care',
    title: 'Outer Hip & IT Band Care',
    purpose: 'Addresses tightness and control through the outer hip, a common area of discomfort for runners.',
    category: 'hip',
    categories: ['hip', 'lower_body', 'problem_areas'],
    targetAreas: ['Outer Hip', 'IT Band'],
    recommendedFrequency: '2–3x/week',
    durationMin: 10,
    evidenceRationale: 'Outer-hip tightness and control are associative observations, not diagnoses, so this pairs stretching with active hip control work rather than passive stretching alone.',
    exercises: [
      { exerciseId: 'standing_it_band_stretch', cues: ['Use the wall for balance'] },
      { exerciseId: 'controlled_hip_cars', cues: ['Full circles, no trunk lean'] },
      { exerciseId: 'glute_bridge', dose: { sets: 2, reps: 12 }, cues: ['Even hips throughout'] },
    ],
  },

  // Back & spine
  {
    id: 'thoracic_rotation_flow',
    title: 'Thoracic Rotation Flow',
    purpose: 'A flowing sequence to build rotational mobility through the mid-back.',
    category: 'back_spine',
    categories: ['back_spine', 'upper_body'],
    targetAreas: ['Upper Back', 'Thoracic Spine'],
    recommendedFrequency: '2–3x/week',
    durationMin: 8,
    evidenceRationale: 'Dynamic thoracic mobility acutely increases rotational range of motion without a performance cost.',
    exercises: [
      { exerciseId: 'thoracic_open_books', dose: { reps: 10 }, cues: ['Follow your hand with your eyes'] },
      { exerciseId: 'seated_spinal_twist', cues: ['Lead with the chest'] },
      { exerciseId: 'cat_cow', cues: ['Move with your breath'] },
    ],
  },
  {
    id: 'low_back_daily_reset',
    title: 'Low Back Daily Reset',
    purpose: 'A gentle daily sequence to ease general low-back stiffness.',
    category: 'back_spine',
    categories: ['back_spine', 'full_body', 'walking_readiness'],
    targetAreas: ['Low Back'],
    recommendedFrequency: 'Daily, as needed',
    durationMin: 8,
    evidenceRationale: 'Gentle, pain-free spinal movement and breathing-paired positions support comfort without the injury-prevention claims stretching alone cannot support.',
    exercises: [
      { exerciseId: 'cat_cow', cues: ['Small, pain-free range'] },
      { exerciseId: 'childs_pose_breathing', dose: { timeSec: 90 }, cues: ['Let the breath do the work'] },
      { exerciseId: 'seated_spinal_twist', cues: ['Gentle rotation only'] },
    ],
  },
  {
    id: 'cat_cow_and_breathing_flow',
    title: 'Cat-Cow & Breathing Flow',
    purpose: 'A slow, breath-led spinal flow for general comfort and mobility.',
    category: 'back_spine',
    categories: ['back_spine', 'full_body'],
    targetAreas: ['Spine', 'Core'],
    recommendedFrequency: 'Daily, as needed',
    durationMin: 6,
    evidenceRationale: 'Slow, breath-synchronized spinal movement is low-risk and commonly used to support comfort and body awareness.',
    exercises: [
      { exerciseId: 'cat_cow', dose: { reps: 12 }, cues: ['Sync with your breath'] },
      { exerciseId: 'childs_pose_breathing', cues: ['Rest here as long as feels good'] },
    ],
  },
  {
    id: 'seated_spinal_mobility',
    title: 'Seated Spinal Mobility',
    purpose: 'A chair-friendly rotation and breathing sequence for days when floor work is not practical.',
    category: 'back_spine',
    categories: ['back_spine', 'walking_readiness', 'upper_body'],
    targetAreas: ['Spine', 'Upper Back'],
    recommendedFrequency: 'Daily, as needed',
    durationMin: 6,
    evidenceRationale: 'Seated rotational work offers a low-barrier way to maintain spinal mobility when floor-based options are not accessible.',
    exercises: [
      { exerciseId: 'seated_spinal_twist', dose: { holdSec: 25 }, cues: ['Rotate from the trunk'] },
      { exerciseId: 'shoulder_wall_slides', cues: ['Control the slide in both directions'] },
    ],
  },

  // Upper body
  {
    id: 'shoulder_and_thoracic_combo',
    title: 'Shoulder & Thoracic Combo',
    purpose: 'Combines shoulder and mid-back mobility to support a relaxed, tall running posture.',
    category: 'upper_body',
    categories: ['upper_body', 'back_spine'],
    targetAreas: ['Shoulders', 'Upper Back'],
    recommendedFrequency: '2–3x/week',
    durationMin: 8,
    evidenceRationale: 'Dynamic shoulder and thoracic mobility acutely increases range of motion without a performance cost, supporting relaxed arm swing.',
    exercises: [
      { exerciseId: 'shoulder_wall_slides', cues: ['Keep low back flat against the wall'] },
      { exerciseId: 'thoracic_open_books', cues: ['Follow your hand with your eyes'] },
    ],
  },
  {
    id: 'running_posture_reset',
    title: 'Running Posture Reset',
    purpose: 'Targets the upper-back and chest tightness that can round shoulders forward during running.',
    category: 'upper_body',
    categories: ['upper_body', 'back_spine', 'running_readiness'],
    targetAreas: ['Chest', 'Upper Back'],
    recommendedFrequency: '2–3x/week',
    durationMin: 8,
    evidenceRationale: 'Improving thoracic extension and chest range of motion may support a taller running posture, though posture-injury links remain associative.',
    exercises: [
      { exerciseId: 'thoracic_open_books', cues: ['Open the chest fully'] },
      { exerciseId: 'shoulder_wall_slides', dose: { reps: 12 }, cues: ['Smooth, controlled slide'] },
      { exerciseId: 'worlds_greatest_stretch', cues: ['Emphasize the chest-opening rotation'] },
    ],
  },
  {
    id: 'desk_break_mobility',
    title: 'Desk-Break Mobility',
    purpose: 'A short sequence to counter stiffness from long periods of sitting, ahead of or between runs.',
    category: 'upper_body',
    categories: ['upper_body', 'back_spine', 'walking_readiness'],
    targetAreas: ['Upper Back', 'Hips'],
    recommendedFrequency: 'Daily, as needed',
    durationMin: 6,
    evidenceRationale: 'Brief mobility breaks during prolonged sitting support comfort and range of motion without requiring dedicated training time.',
    exercises: [
      { exerciseId: 'cat_cow', cues: ['Small, easy range'] },
      { exerciseId: 'shoulder_wall_slides', cues: ['Reset posture'] },
      { exerciseId: 'hip_flexor_stretch_kneeling', dose: { holdSec: 20 }, cues: ['Quick hip-flexor release'] },
    ],
  },

  // Lower body
  {
    id: 'calf_and_ankle_lower_body',
    title: 'Calf & Ankle Lower-Body Session',
    purpose: 'A lower-leg-focused session pairing ankle range with calf strength and stretch.',
    category: 'lower_body',
    categories: ['lower_body', 'ankle'],
    targetAreas: ['Calf', 'Ankle'],
    recommendedFrequency: '2–3x/week',
    durationMin: 12,
    evidenceRationale: 'Pairing ankle range work with calf strengthening addresses both the joint and muscle-tendon components that limit lower-leg mobility.',
    exercises: [
      { exerciseId: 'ankle_rocks', cues: ['Warm up first'] },
      { exerciseId: 'single_leg_heel_raise', dose: { sets: 3, reps: 15 }, cues: ['Controlled tempo'] },
      { exerciseId: 'calf_stretch_gastroc', cues: ['Full stretch after loading'] },
    ],
  },
  {
    id: 'hip_and_glute_lower_body',
    title: 'Hip & Glute Lower-Body Session',
    purpose: 'Combines hip mobility with glute strengthening for lower-body running support.',
    category: 'lower_body',
    categories: ['lower_body', 'hip'],
    targetAreas: ['Hips', 'Glutes'],
    recommendedFrequency: '2–3x/week',
    durationMin: 12,
    evidenceRationale: 'Hip and glute strengthening pairs well with mobility work to support movement quality through the running stride.',
    exercises: [
      { exerciseId: 'hip_flexor_stretch_kneeling', cues: ['Torso tall'] },
      { exerciseId: 'glute_bridge', dose: { sets: 3, reps: 12 }, cues: ['Squeeze at the top'] },
      { exerciseId: 'controlled_hip_cars', cues: ['Slow, full circles'] },
    ],
  },
  {
    id: 'hamstring_focused_mobility',
    title: 'Hamstring-Focused Mobility',
    purpose: 'Targets hamstring range and control with gentle nerve-glide style movement.',
    category: 'lower_body',
    categories: ['lower_body', 'problem_areas'],
    targetAreas: ['Hamstrings'],
    recommendedFrequency: '2–3x/week',
    durationMin: 8,
    evidenceRationale: 'Gentle, moving hamstring work builds range without the intensity of a held stretch, appropriate for irritable or sensitive tissue.',
    exercises: [
      { exerciseId: 'hamstring_flossing', dose: { reps: 12 }, cues: ['Small, smooth range'] },
      { exerciseId: 'worlds_greatest_stretch', cues: ['Emphasize the hamstring reach phase'] },
    ],
  },
  {
    id: 'quad_and_hip_flexor_lower_body',
    title: 'Quad & Hip Flexor Lower-Body Session',
    purpose: 'Addresses tightness through the quads and hip flexors that can build up with high running volume.',
    category: 'lower_body',
    categories: ['lower_body', 'hip'],
    targetAreas: ['Quads', 'Hip Flexors'],
    recommendedFrequency: '2–3x/week',
    durationMin: 10,
    evidenceRationale: 'Consistent stretching of the quads and hip flexors supports range of motion in muscle groups heavily used during the running stride.',
    exercises: [
      { exerciseId: 'standing_quad_stretch', cues: ['Knees close together'] },
      { exerciseId: 'couch_stretch', cues: ['Ease in gradually'] },
      { exerciseId: 'hip_flexor_stretch_kneeling', cues: ['Torso tall'] },
    ],
  },

  // Full body
  {
    id: 'full_body_mobility_a',
    title: 'Full-Body Mobility — Session A',
    purpose: 'A well-rounded mobility session covering ankles, hips, and spine for general running support.',
    category: 'full_body',
    categories: ['full_body', 'running_readiness'],
    targetAreas: ['Ankles', 'Hips', 'Spine'],
    recommendedFrequency: '2x/week',
    durationMin: 15,
    evidenceRationale: 'A broad mobility session covering the major running-relevant joints reflects the full range of evidence-supported approaches.',
    exercises: [
      { exerciseId: 'ankle_rocks', cues: ['Warm up first'] },
      { exerciseId: 'worlds_greatest_stretch', cues: ['Flow through each position'] },
      { exerciseId: 'thoracic_open_books', cues: ['Rotate with control'] },
      { exerciseId: 'glute_bridge', cues: ['Full squeeze at the top'] },
    ],
  },
  {
    id: 'full_body_mobility_b',
    title: 'Full-Body Mobility — Session B',
    purpose: 'A second full-body variation for rotating through the week without repeating the same session.',
    category: 'full_body',
    categories: ['full_body', 'running_readiness'],
    targetAreas: ['Hips', 'Calves', 'Upper Back'],
    recommendedFrequency: '2x/week',
    durationMin: 15,
    evidenceRationale: 'Rotating between full-body mobility sessions maintains variety while covering the same evidence-supported areas.',
    exercises: [
      { exerciseId: 'calf_stretch_gastroc', cues: ['Steady hold'] },
      { exerciseId: 'ninety_ninety_hip_switches', cues: ['Control the switch'] },
      { exerciseId: 'thoracic_open_books', cues: ['Follow your hand'] },
      { exerciseId: 'squat_pry', dose: { timeSec: 20 }, cues: ['Comfortable depth only'] },
    ],
  },
  {
    id: 'full_body_mobility_c',
    title: 'Full-Body Mobility — Session C',
    purpose: 'A third full-body variation emphasizing loaded control alongside stretching.',
    category: 'full_body',
    categories: ['full_body', 'problem_areas'],
    targetAreas: ['Hips', 'Glutes', 'Ankles'],
    recommendedFrequency: '2x/week',
    durationMin: 15,
    evidenceRationale: 'Combining loaded control work with mobility reflects the strongest available evidence for supporting movement quality.',
    exercises: [
      { exerciseId: 'glute_bridge', dose: { sets: 3, reps: 12 }, cues: ['Squeeze at the top'] },
      { exerciseId: 'controlled_hip_cars', cues: ['Full circles'] },
      { exerciseId: 'single_leg_heel_raise', dose: { sets: 2, reps: 12 }, cues: ['Controlled tempo'] },
    ],
  },
  {
    id: 'quick_ten_minute_full_body',
    title: 'Quick 10-Minute Full-Body Mobility',
    purpose: 'A condensed full-body session for days with limited time.',
    category: 'full_body',
    categories: ['full_body', 'running_readiness', 'walking_readiness'],
    targetAreas: ['Ankles', 'Hips', 'Spine'],
    recommendedFrequency: 'As time allows',
    durationMin: 10,
    evidenceRationale: 'A shorter, well-rounded session still covers the major running-relevant areas when time is limited.',
    exercises: [
      { exerciseId: 'ankle_rocks', cues: ['Quick warm-up'] },
      { exerciseId: 'worlds_greatest_stretch', dose: { reps: 3 }, cues: ['Flow through smoothly'] },
      { exerciseId: 'cat_cow', dose: { reps: 8 }, cues: ['Move with your breath'] },
    ],
  },

  // Problem areas
  {
    id: 'trunk_pelvic_control_focus',
    title: 'Trunk & Pelvic Control Focus',
    purpose: 'Targeted control work for athletes whose readiness assessment flagged trunk or pelvic control.',
    category: 'problem_areas',
    categories: ['problem_areas', 'hip', 'lower_body'],
    targetAreas: ['Trunk', 'Pelvis', 'Hips'],
    recommendedFrequency: '2–3x/week',
    durationMin: 12,
    evidenceRationale: 'Trunk and pelvic control observations are associative rather than causal, so this emphasizes hip and glute strengthening — the modality with the strongest evidence for supporting movement quality.',
    linkedAssessmentFinding: 'trunk_pelvic_control',
    exercises: [
      { exerciseId: 'glute_bridge', dose: { sets: 3, reps: 12 }, cues: ['Even hips, no rotation'] },
      { exerciseId: 'controlled_hip_cars', cues: ['Keep the trunk quiet'] },
      { exerciseId: 'squat_pry', dose: { timeSec: 20 }, cues: ['Stable, comfortable depth'] },
    ],
  },
  {
    id: 'calf_capacity_problem_area',
    title: 'Calf Capacity — Problem Area Focus',
    purpose: 'A more targeted version of calf capacity work for athletes flagged with reduced calf capacity.',
    category: 'problem_areas',
    categories: ['problem_areas', 'ankle', 'lower_body'],
    targetAreas: ['Calf', 'Soleus', 'Achilles'],
    recommendedFrequency: '3x/week',
    durationMin: 12,
    evidenceRationale: 'Progressive calf loading is a cornerstone of clinical guidance for calf and Achilles capacity concerns flagged on a readiness screen.',
    cautionNote: 'If you have current Achilles or calf pain, ease into this and consider checking with a clinician before adding load.',
    linkedAssessmentFinding: 'calf_capacity',
    exercises: [
      { exerciseId: 'single_leg_heel_raise', dose: { sets: 4, reps: 15 }, cues: ['Full range, controlled tempo'] },
      { exerciseId: 'calf_stretch_gastroc', cues: ['Steady hold'] },
      { exerciseId: 'soleus_stretch', cues: ['Bent-knee version'] },
    ],
  },
  {
    id: 'hip_extension_deficit_focus',
    title: 'Hip Extension Deficit Focus',
    purpose: 'A more targeted version of hip extension work for athletes flagged with limited hip extension.',
    category: 'problem_areas',
    categories: ['problem_areas', 'hip'],
    targetAreas: ['Hip Flexors', 'Quads'],
    recommendedFrequency: '3–4x/week',
    durationMin: 12,
    evidenceRationale: 'Limited hip extension may affect stride mechanics behind the body, and consistent, more frequent stretching supports range of motion over time.',
    linkedAssessmentFinding: 'limited_hip_extension',
    exercises: [
      { exerciseId: 'couch_stretch', dose: { holdSec: 40, sets: 3 }, cues: ['Ease in gradually'] },
      { exerciseId: 'hip_flexor_stretch_kneeling', cues: ['Torso tall'] },
      { exerciseId: 'standing_quad_stretch', cues: ['Knees close together'] },
    ],
  },
  {
    id: 'ankle_dorsiflexion_deficit_focus',
    title: 'Ankle Dorsiflexion Deficit Focus',
    purpose: 'A more targeted version of ankle mobility work for athletes flagged with limited ankle dorsiflexion.',
    category: 'problem_areas',
    categories: ['problem_areas', 'ankle'],
    targetAreas: ['Ankle', 'Calf'],
    recommendedFrequency: '4x/week',
    durationMin: 12,
    evidenceRationale: 'Limited ankle mobility may affect squat depth and landing mechanics, and more frequent, consistent mobility work supports change over time.',
    linkedAssessmentFinding: 'limited_ankle_dorsiflexion',
    exercises: [
      { exerciseId: 'knee_to_wall_ankle_mobilization', dose: { sets: 3, reps: 12 }, cues: ['Track progress each session'] },
      { exerciseId: 'calf_stretch_gastroc', cues: ['Steady hold'] },
      { exerciseId: 'soleus_stretch', cues: ['Bent-knee version'] },
      { exerciseId: 'ankle_alphabet', dose: { timeSec: 30 }, cues: ['Easy, full-range movement'] },
    ],
  },

  // Running readiness
  {
    id: 'race_week_gentle_primer',
    title: 'Race-Week Gentle Primer',
    purpose: 'A light, low-fatigue mobility session appropriate for race week or taper.',
    category: 'running_readiness',
    categories: ['running_readiness', 'pre_run', 'full_body'],
    targetAreas: ['Ankles', 'Hips'],
    recommendedFrequency: '2–3x during race week',
    durationMin: 6,
    evidenceRationale: 'Light dynamic movement maintains readiness without adding the fatigue cost of a full mobility session during a taper.',
    exercises: [
      { exerciseId: 'ankle_rocks', dose: { reps: 8 }, cues: ['Easy, light effort'] },
      { exerciseId: 'worlds_greatest_stretch', dose: { reps: 2 }, cues: ['Gentle, unhurried pace'] },
    ],
  },
  {
    id: 'hill_prep_ankle_calf',
    title: 'Hill-Prep Ankle & Calf Session',
    purpose: 'Prepares the ankles and calves for the added demands of hill running.',
    category: 'running_readiness',
    categories: ['running_readiness', 'ankle', 'lower_body'],
    targetAreas: ['Ankle', 'Calf'],
    recommendedFrequency: '2x/week leading into hill work',
    durationMin: 10,
    evidenceRationale: 'Hill running increases ankle and calf demand, and progressive calf loading supports the capacity needed for that added demand.',
    exercises: [
      { exerciseId: 'ankle_rocks', cues: ['Warm up first'] },
      { exerciseId: 'single_leg_heel_raise', dose: { sets: 3, reps: 15 }, cues: ['Controlled tempo'] },
      { exerciseId: 'knee_to_wall_ankle_mobilization', cues: ['Heel flat throughout'] },
    ],
  },
  {
    id: 'speed_work_prep_mobility',
    title: 'Speed-Work Prep Mobility',
    purpose: 'Dynamic mobility to prepare the hips and hamstrings before faster running.',
    category: 'running_readiness',
    categories: ['running_readiness', 'pre_run', 'lower_body'],
    targetAreas: ['Hips', 'Hamstrings'],
    recommendedFrequency: 'Before speed sessions',
    durationMin: 8,
    evidenceRationale: 'Dynamic mobility increases range of motion and readiness without the transient force loss long static holds can cause right before fast running.',
    exercises: [
      { exerciseId: 'lunge_with_rotation', cues: ['Rotate from the trunk'] },
      { exerciseId: 'hamstring_flossing', dose: { reps: 12 }, cues: ['Small, smooth range'] },
      { exerciseId: 'controlled_hip_cars', dose: { reps: 4 }, cues: ['Full, controlled circles'] },
    ],
  },
  {
    id: 'long_run_prep_and_recovery',
    title: 'Long-Run Prep & Recovery Combo',
    purpose: 'A combined pre- and post-long-run mobility approach for the week\'s biggest session.',
    category: 'running_readiness',
    categories: ['running_readiness', 'pre_run', 'post_run'],
    targetAreas: ['Ankles', 'Hips', 'Calves'],
    recommendedFrequency: 'Around your weekly long run',
    durationMin: 14,
    evidenceRationale: 'Pairing a dynamic pre-run primer with post-run static stretching reflects the current evidence on timing mobility work around effort.',
    exercises: [
      { exerciseId: 'ankle_rocks', cues: ['Pre-run: warm up first'] },
      { exerciseId: 'worlds_greatest_stretch', cues: ['Pre-run: flow through smoothly'] },
      { exerciseId: 'calf_stretch_gastroc', cues: ['Post-run: steady hold'] },
      { exerciseId: 'childs_pose_breathing', cues: ['Post-run: slow, full breaths'] },
    ],
  },

  // Walking readiness
  {
    id: 'gentle_daily_walk_prep',
    title: 'Gentle Daily Walk Prep',
    purpose: 'A low-intensity mobility sequence appropriate before daily walking.',
    category: 'walking_readiness',
    categories: ['walking_readiness', 'pre_run', 'full_body'],
    targetAreas: ['Ankles', 'Hips'],
    recommendedFrequency: 'Before daily walks',
    durationMin: 5,
    evidenceRationale: 'Light dynamic movement supports comfortable walking mechanics without requiring a high-intensity warm-up.',
    exercises: [
      { exerciseId: 'ankle_rocks', dose: { reps: 8 }, cues: ['Easy, light effort'] },
      { exerciseId: 'cat_cow', dose: { reps: 8 }, cues: ['Small, comfortable range'] },
    ],
  },
  {
    id: 'joint_friendly_full_body_walking',
    title: 'Joint-Friendly Full-Body Session',
    purpose: 'A gentle, low-impact full-body mobility session suited to walking-focused athletes.',
    category: 'walking_readiness',
    categories: ['walking_readiness', 'full_body'],
    targetAreas: ['Ankles', 'Hips', 'Spine'],
    recommendedFrequency: '2–3x/week',
    durationMin: 10,
    evidenceRationale: 'Low-impact mobility work supports comfortable movement without the loading demands of running-specific sessions.',
    exercises: [
      { exerciseId: 'cat_cow', cues: ['Small, pain-free range'] },
      { exerciseId: 'figure_four_glute_stretch', cues: ['Relax into the floor'] },
      { exerciseId: 'ankle_alphabet', dose: { timeSec: 30 }, cues: ['Easy, exploratory movement'] },
    ],
  },
  {
    id: 'balance_and_stability_walking',
    title: 'Balance & Stability for Walking',
    purpose: 'Builds single-leg balance and control to support stability during walking.',
    category: 'walking_readiness',
    categories: ['walking_readiness', 'lower_body', 'problem_areas'],
    targetAreas: ['Balance', 'Hips', 'Ankle'],
    recommendedFrequency: '2–3x/week',
    durationMin: 10,
    evidenceRationale: 'Single-leg balance and control work is low-risk and supports movement-quality measures relevant to stable walking mechanics.',
    exercises: [
      { exerciseId: 'single_leg_heel_raise', dose: { sets: 2, reps: 10 }, cues: ['Balance first, height second'] },
      { exerciseId: 'controlled_hip_cars', dose: { reps: 4 }, cues: ['Slow and controlled'] },
      { exerciseId: 'glute_bridge', dose: { sets: 2, reps: 10 }, cues: ['Even hips throughout'] },
    ],
  },
];

export function getMobilityWorkout(id: string): MobilityWorkout | undefined {
  return MOBILITY_WORKOUTS.find(w => w.id === id);
}

export function getMobilityWorkoutsByCategory(category: MobilityCategory): MobilityWorkout[] {
  return MOBILITY_WORKOUTS.filter(w => w.categories.includes(category));
}

export const MOBILITY_CATEGORY_LABELS: Record<MobilityCategory, string> = {
  full_body: 'Full Body',
  problem_areas: 'Problem Areas',
  ankle: 'Ankle',
  hip: 'Hip',
  back_spine: 'Back & Spine',
  pre_run: 'Pre-Run',
  post_run: 'Post-Run',
  upper_body: 'Upper Body',
  lower_body: 'Lower Body',
  running_readiness: 'Running Readiness',
  walking_readiness: 'Walking Readiness',
};
