// ─── Mobility Exercise & Workout Bank (Build 34, Wave 1B) ─────────────────────
//
// Content contract: docs/movement-readiness-evidence.md. Language stays inside
// the allowed set ("may affect", "may contribute to", "worth monitoring",
// "consider addressing") and never claims diagnosis, injury causation, or
// injury prevention. Coaching tone: gentle, breathe, back off if sharp pain —
// never "push through" or "no pain no gain".
//
// AI REPLACEMENT HOOK: this bank is a static seed. A future engine can
// personalize dose/selection per athlete without changing the MobilityWorkout
// / MobilityExercise shape or downstream store/UI.

import type { MobilityCategory, MobilityExercise, MobilityWorkout } from '../types/mobility';

// ─── Exercises ─────────────────────────────────────────────────────────────────

export const MOBILITY_EXERCISES: MobilityExercise[] = [
  {
    id: 'knee_to_wall_ankle_mobilization',
    name: 'Knee-to-Wall Ankle Mobilization',
    targetArea: 'Ankle · Calf',
    howTo: [
      'Face a wall in a half-kneeling position, front foot a few inches back from the wall.',
      'Keeping your front heel flat on the floor, drive your front knee forward toward the wall.',
      'Touch the wall with your knee if you can, then return to start — that is one rep.',
      'If your heel lifts before your knee reaches the wall, step the foot back slightly.',
    ],
    commonMistakes: [
      'Letting the heel lift off the ground to fake more range.',
      'Rushing the rep instead of controlling the forward glide.',
      'Turning the front foot outward to make the knee travel look bigger.',
    ],
    whatItShouldFeelLike: 'A mild stretch through the front of the ankle and calf — controlled, not painful.',
    whenToStopOrModify: 'Keep it gentle. Move only as far as your heel stays flat, and back off if you feel sharp pain.',
    linkedFinding: 'limited_ankle_dorsiflexion',
    dose: { sets: 2, reps: 10, perSide: true },
  },
  {
    id: 'calf_stretch_gastroc',
    name: 'Calf Stretch (Straight-Knee)',
    targetArea: 'Calf · Gastrocnemius',
    howTo: [
      'Stand facing a wall, hands on the wall for balance.',
      'Step one foot back, keeping that back knee straight and heel on the floor.',
      'Lean your hips forward until you feel a stretch up the back of the lower leg.',
      'Hold, breathing steadily, then switch sides.',
    ],
    commonMistakes: [
      'Letting the back heel lift off the floor.',
      'Bouncing instead of holding a steady position.',
      'Rotating the back foot inward instead of pointing it straight ahead.',
    ],
    whatItShouldFeelLike: 'A gentle, steady pull through the upper calf — comfortable enough to hold while breathing normally.',
    whenToStopOrModify: 'Ease off the lean if it feels sharp or if your knee complains. This should feel like a stretch, not a strain.',
    dose: { holdSec: 30, sets: 2, perSide: true },
  },
  {
    id: 'soleus_stretch',
    name: 'Soleus Stretch (Bent-Knee)',
    targetArea: 'Calf · Soleus',
    howTo: [
      'Same wall position as the calf stretch, but bend the back knee slightly.',
      'Keep the back heel down and shift your hips forward and down.',
      'You should feel this stretch lower, closer to the Achilles, than the straight-knee version.',
      'Hold, breathing steadily, then switch sides.',
    ],
    commonMistakes: [
      'Straightening the back knee, which shifts the stretch to the calf instead.',
      'Letting the back heel come up.',
      'Holding your breath through the hold.',
    ],
    whatItShouldFeelLike: 'A gentle stretch lower in the calf, nearer the ankle, without pinching or sharp discomfort.',
    whenToStopOrModify: 'Keep the hold light. If it becomes sharp or throbbing, come out of the stretch and shorten the hold next time.',
    dose: { holdSec: 30, sets: 2, perSide: true },
  },
  {
    id: 'hip_flexor_stretch_kneeling',
    name: 'Half-Kneeling Hip Flexor Stretch',
    targetArea: 'Hip Flexors',
    howTo: [
      'Kneel on one knee with the other foot planted in front, both knees near 90°.',
      'Tuck your tailbone slightly and gently shift your hips forward.',
      'Keep your torso tall — avoid arching your lower back to get more range.',
      'Hold, breathing steadily, then switch sides.',
    ],
    commonMistakes: [
      'Arching the lower back to force a bigger stretch.',
      'Shifting weight onto the back knee instead of driving the hips forward.',
      'Rushing the hold instead of easing in gradually.',
    ],
    whatItShouldFeelLike: 'A gentle stretch along the front of the hip and upper thigh of the back leg.',
    whenToStopOrModify: 'Back off the forward shift if you feel pinching in the front of the hip or low back discomfort — this should stay a mild, breathable stretch.',
    linkedFinding: 'limited_hip_extension',
    dose: { holdSec: 30, sets: 2, perSide: true },
  },
  {
    id: 'couch_stretch',
    name: 'Couch Stretch',
    targetArea: 'Hip Flexors · Quads',
    howTo: [
      'Kneel in front of a couch or wall, back shin resting vertically against it.',
      'Keep the front foot planted and torso upright, tucking the tailbone slightly.',
      'Gently rise the torso taller to deepen the stretch through the back leg\'s hip and thigh.',
      'Hold, breathing steadily, then switch sides.',
    ],
    commonMistakes: [
      'Going for maximum range on day one instead of easing in gradually.',
      'Letting the lower back arch to compensate.',
      'Holding tension in the shoulders instead of relaxing into the position.',
    ],
    whatItShouldFeelLike: 'A noticeable but tolerable stretch through the front of the hip and thigh — more intense than the kneeling version.',
    whenToStopOrModify: 'This is a deeper stretch than most on this list — ease in slowly, use a shallower knee bend if it feels like too much, and stop if you feel sharp or pinching pain in the knee or hip.',
    linkedFinding: 'limited_hip_extension',
    dose: { holdSec: 30, sets: 2, perSide: true },
  },
  {
    id: 'ninety_ninety_hip_switches',
    name: '90/90 Hip Switches',
    targetArea: 'Hips · Rotation',
    howTo: [
      'Sit on the floor with both knees bent near 90°, one leg in front, one to the side.',
      'Keeping your chest tall, lift both knees slightly and rotate to switch legs to the other side.',
      'Control the movement down on both sides rather than dropping into it.',
      'Continue alternating for the prescribed reps.',
    ],
    commonMistakes: [
      'Using your hands to yank the legs through instead of rotating from the hips.',
      'Letting the torso collapse forward to help the legs switch.',
      'Rushing the switch instead of controlling it in both directions.',
    ],
    whatItShouldFeelLike: 'Work through a rotational range in the hips — some effort to control, but not painful.',
    whenToStopOrModify: 'Slow down or use a hand for support if balance is hard. Stop if you feel pinching in the front of the hip.',
    dose: { sets: 2, reps: 10 },
  },
  {
    id: 'adductor_rockbacks',
    name: 'Adductor Rockbacks',
    targetArea: 'Inner Thigh · Adductors',
    howTo: [
      'Start in a wide kneeling straddle, one leg bent at 90°, the other extended out to the side.',
      'Keeping both feet flat/planted, rock your hips back toward the bent-knee heel.',
      'Feel the stretch build through the inner thigh of the extended leg, then rock forward to release.',
      'Repeat, then switch sides.',
    ],
    commonMistakes: [
      'Rounding the low back instead of hinging from the hips.',
      'Forcing the range instead of rocking gently back and forth.',
      'Letting the extended leg\'s foot roll instead of staying planted.',
    ],
    whatItShouldFeelLike: 'A building, controllable stretch through the inner thigh as you rock back — never a sharp pull.',
    whenToStopOrModify: 'Rock back only as far as feels smooth. Stop if you feel sharp groin pain and reduce the range next time.',
    dose: { sets: 2, reps: 8, perSide: true },
  },
  {
    id: 'thoracic_open_books',
    name: 'Thoracic Open Books',
    targetArea: 'Upper Back · Thoracic Spine',
    howTo: [
      'Lie on your side with knees stacked and bent, arms extended together in front of you.',
      'Keeping your bottom knee anchored, rotate your top arm and chest open toward the ceiling and floor behind you.',
      'Follow your top hand with your eyes as you rotate, then return to start.',
      'Complete the reps, then switch sides.',
    ],
    commonMistakes: [
      'Letting the hips and knees rotate along with the chest, which removes the stretch.',
      'Rushing through the range instead of rotating with control.',
      'Holding the breath through the rotation.',
    ],
    whatItShouldFeelLike: 'A mobilizing stretch through the mid-back and chest as you rotate — controlled, not forced.',
    whenToStopOrModify: 'Keep the bottom knee anchored and only rotate as far as stays comfortable. Ease off if you feel sharp pain rather than a stretch.',
    dose: { sets: 2, reps: 8, perSide: true },
  },
  {
    id: 'cat_cow',
    name: 'Cat-Cow',
    targetArea: 'Spine · Core',
    howTo: [
      'Start on hands and knees, wrists under shoulders, knees under hips.',
      'Inhale, drop your belly and lift your chest and tailbone (cow).',
      'Exhale, round your spine toward the ceiling, tucking chin and tailbone (cat).',
      'Flow slowly between the two positions with your breath.',
    ],
    commonMistakes: [
      'Moving faster than your breath instead of syncing the two.',
      'Only moving the neck instead of flowing through the whole spine.',
      'Locking the elbows instead of keeping them soft.',
    ],
    whatItShouldFeelLike: 'A gentle, easy wave through the spine — this should feel good, not effortful.',
    whenToStopOrModify: 'Keep the range small and pain-free. If any position pinches, shrink the range rather than pushing through it.',
    dose: { sets: 2, reps: 10 },
  },
  {
    id: 'childs_pose_breathing',
    name: "Child's Pose Breathing",
    targetArea: 'Low Back · Hips',
    howTo: [
      'Kneel and sit your hips back toward your heels, reaching your arms forward on the floor.',
      'Let your chest and forehead relax down.',
      'Breathe slowly and fully into your low back and sides for the prescribed time.',
      'Rise slowly when finished.',
    ],
    commonMistakes: [
      'Holding tension in the shoulders instead of relaxing them down.',
      'Taking shallow chest breaths instead of full breaths into the back.',
      'Forcing the hips all the way to the heels if that is uncomfortable on the knees.',
    ],
    whatItShouldFeelLike: 'A calm, passive stretch through the low back and hips paired with easy breathing.',
    whenToStopOrModify: 'Use a cushion under the hips or knees if this pinches. It should feel restful, not painful.',
    dose: { timeSec: 60, sets: 1 },
  },
  {
    id: 'worlds_greatest_stretch',
    name: "World's Greatest Stretch",
    targetArea: 'Full Body · Hips, Thoracic, Hamstrings',
    howTo: [
      'Step into a long lunge, both hands planted inside the front foot.',
      'Rotate your front-side elbow toward the ceiling, opening your chest.',
      'Return the hand down, then straighten the front leg to feel the hamstring, keeping hands on the floor.',
      'Bend the knee back into the lunge and repeat, then switch sides.',
    ],
    commonMistakes: [
      'Letting the front knee collapse inward during the lunge.',
      'Rushing through the sequence instead of pausing briefly in each position.',
      'Forcing the rotation instead of moving within a comfortable range.',
    ],
    whatItShouldFeelLike: 'A moving stretch through the hip, chest, and hamstring of the front leg — dynamic and flowing, not held tension.',
    whenToStopOrModify: 'Use a shorter stance or drop the back knee to the floor if balance is hard. Stay within a pain-free range throughout.',
    dose: { sets: 2, reps: 5, perSide: true },
  },
  {
    id: 'ankle_rocks',
    name: 'Ankle Rocks',
    targetArea: 'Ankle',
    howTo: [
      'Stand tall, feet hip-width apart, hands on hips or a wall for balance.',
      'Rock your weight forward over your toes, letting your ankles bend, heels staying down.',
      'Rock back slightly onto your heels, then forward again.',
      'Keep the motion smooth and continuous for the prescribed reps.',
    ],
    commonMistakes: [
      'Letting the heels lift during the forward rock.',
      'Bending at the hips instead of driving the motion through the ankles.',
      'Rocking too fast to control the position.',
    ],
    whatItShouldFeelLike: 'A light, rhythmic loading through the ankles — easy and warm, not a deep stretch.',
    whenToStopOrModify: 'Use a wall for balance if needed. Shorten the range if you feel any sharp pinch at the front of the ankle.',
    dose: { sets: 2, reps: 12, perSide: false },
  },
  {
    id: 'lunge_with_rotation',
    name: 'Lunge with Rotation',
    targetArea: 'Hips · Thoracic Spine',
    howTo: [
      'Step into a forward lunge, both knees near 90°.',
      'Rotate your torso and both arms toward the front-leg side.',
      'Rotate back to center, then push back to standing.',
      'Repeat, alternating legs or completing one side at a time as prescribed.',
    ],
    commonMistakes: [
      'Rotating from the low back instead of the mid-back and hips together.',
      'Letting the front knee drift past the toes or collapse inward.',
      'Losing balance by rotating too far, too fast.',
    ],
    whatItShouldFeelLike: 'A dynamic, warming stretch through the hip and trunk — controlled effort, not strain.',
    whenToStopOrModify: 'Shorten the lunge depth or rotation range if balance or comfort is an issue. Keep it smooth and pain-free.',
    dose: { sets: 2, reps: 8, perSide: true },
  },
  {
    id: 'hamstring_flossing',
    name: 'Hamstring Flossing',
    targetArea: 'Hamstrings · Nerve Glide',
    howTo: [
      'Stand tall, or hinge slightly at the hips, one heel propped in front on a low surface (or lifted, knee straight).',
      'Keep a slight bend in your standing knee and hinge your hips forward gently, then return upright.',
      'Move in and out of the position smoothly rather than holding a static stretch.',
      'Repeat, then switch legs.',
    ],
    commonMistakes: [
      'Rounding the back to force more range at the hamstring.',
      'Locking the front knee hard, which can feel pinching rather than stretching.',
      'Moving too fast to control the hinge.',
    ],
    whatItShouldFeelLike: 'A mild, moving tension behind the thigh that eases as you move — not a held, intense stretch.',
    whenToStopOrModify: 'Keep the range small if you feel any sharp or nerve-like tingling, and ease back into a smaller motion.',
    dose: { sets: 2, reps: 10, perSide: true },
  },
  {
    id: 'glute_bridge',
    name: 'Glute Bridge',
    targetArea: 'Glutes · Hip Extension',
    howTo: [
      'Lie on your back, knees bent, feet flat about hip-width apart.',
      'Squeeze your glutes and press through your heels to lift your hips until your body forms a straight line from knees to shoulders.',
      'Pause briefly at the top, then lower with control.',
      'Repeat for the prescribed reps.',
    ],
    commonMistakes: [
      'Overarching the low back at the top instead of squeezing the glutes.',
      'Pushing through the toes instead of the heels.',
      'Dropping quickly instead of lowering under control.',
    ],
    whatItShouldFeelLike: 'Working effort in the glutes and hamstrings at the top of the movement — not your low back.',
    whenToStopOrModify: 'Reduce the range or the number of reps if your low back takes over the effort. This is loaded control work, not a stretch — some muscular fatigue is expected.',
    dose: { sets: 3, reps: 12 },
  },
  {
    id: 'controlled_hip_cars',
    name: 'Controlled Hip CARs',
    targetArea: 'Hip Joint · Rotational Control',
    howTo: [
      'Stand tall holding a wall or sturdy surface for balance.',
      'Lift one knee up, then rotate it out to the side, then reach it back behind you, keeping the motion slow and controlled.',
      'Trace the largest smooth circle you can control without shifting your trunk.',
      'Complete the reps, then switch directions or legs as prescribed.',
    ],
    commonMistakes: [
      'Letting the torso lean or twist to fake extra hip range.',
      'Moving fast through the circle instead of staying slow and controlled.',
      'Holding the breath through the movement.',
    ],
    whatItShouldFeelLike: 'Controlled effort through a full circle at the hip — like actively "owning" the range, not passively stretching into it.',
    whenToStopOrModify: 'Shrink the circle if you can\'t keep the trunk still, and stop if you feel pinching at the front or back of the hip.',
    dose: { sets: 2, reps: 5, perSide: true },
  },
  {
    id: 'squat_pry',
    name: 'Squat Pry',
    targetArea: 'Ankles · Hips · Groin',
    howTo: [
      'Lower into the deepest comfortable squat, feet flat, holding onto something for balance if needed.',
      'Rest your elbows against the inside of your knees.',
      'Gently pry your knees outward using your elbows, rocking side to side.',
      'Hold the general position for the prescribed time, moving gently within it.',
    ],
    commonMistakes: [
      'Letting the heels lift to fake a deeper squat.',
      'Forcing the knees open aggressively instead of prying gently.',
      'Rounding the low back heavily instead of keeping the chest reasonably tall.',
    ],
    whatItShouldFeelLike: 'A full-range stretch through the ankles, hips, and inner thighs while your muscles work to hold the position.',
    whenToStopOrModify: 'Elevate your heels on a rolled towel if you can\'t keep them flat. Stop prying if you feel sharp joint pain.',
    dose: { timeSec: 30, sets: 2 },
  },
  {
    id: 'single_leg_heel_raise',
    name: 'Single-Leg Heel Raise (Capacity Drill)',
    targetArea: 'Calf · Soleus Capacity',
    howTo: [
      'Stand on one leg, holding a wall or rail for light balance support.',
      'Rise onto the ball of your foot as high as you can, then lower with control.',
      'Keep your knee mostly straight and your weight centered over the big toe.',
      'Repeat for the prescribed reps, then switch legs.',
    ],
    commonMistakes: [
      'Using the support hand to pull yourself up instead of pushing through the calf.',
      'Dropping quickly instead of lowering under control.',
      'Letting the ankle roll outward or inward through the movement.',
    ],
    whatItShouldFeelLike: 'Building muscular fatigue in the calf as reps accumulate — this is a capacity drill, so working effort is expected.',
    whenToStopOrModify: 'Stop the set if you feel sharp Achilles or calf pain (distinct from normal working fatigue), and use two hands on support for balance if needed.',
    linkedFinding: 'calf_capacity',
    dose: { sets: 3, reps: 15, perSide: true },
  },
];

export function getMobilityExercise(id: string): MobilityExercise | undefined {
  return MOBILITY_EXERCISES.find(e => e.id === id);
}

// ─── Workouts ──────────────────────────────────────────────────────────────────

export const MOBILITY_WORKOUTS: MobilityWorkout[] = [
  {
    id: 'pre_run_mobility_primer',
    title: 'Pre-Run Mobility Primer',
    purpose: 'A short dynamic warm-up to get your ankles, hips, and spine moving before you run.',
    category: 'pre_run',
    categories: ['pre_run', 'full_body', 'running_readiness', 'walking_readiness'],
    targetAreas: ['Ankles', 'Hips', 'Spine'],
    recommendedFrequency: 'Before every run',
    durationMin: 8,
    evidenceRationale: 'Dynamic mobility increases range of motion without the transient force loss that long static holds can cause right before intense effort, so primers use movement rather than held stretches.',
    exercises: [
      { exerciseId: 'ankle_rocks', cues: ['Keep heels down', 'Smooth, rhythmic motion'] },
      { exerciseId: 'cat_cow', cues: ['Move with your breath'] },
      { exerciseId: 'worlds_greatest_stretch', cues: ['Pause briefly in each position, don\'t rush'] },
      { exerciseId: 'lunge_with_rotation', cues: ['Rotate from the trunk, not just the arms'] },
      { exerciseId: 'controlled_hip_cars', dose: { reps: 4 }, cues: ['Keep the trunk still, move the hip'] },
      { exerciseId: 'glute_bridge', dose: { sets: 1, reps: 10 }, cues: ['Quick activation set — squeeze at the top'] },
    ],
  },
  {
    id: 'post_run_recovery_mobility',
    title: 'Post-Run Recovery Mobility',
    purpose: 'Static stretches and easy breathing to help your body settle after a run.',
    category: 'post_run',
    categories: ['post_run', 'full_body'],
    targetAreas: ['Calves', 'Hips', 'Low Back'],
    recommendedFrequency: 'After harder or longer runs',
    durationMin: 12,
    evidenceRationale: 'Static stretching reliably improves joint range of motion; used after training rather than immediately before, it carries no meaningful performance downside.',
    exercises: [
      { exerciseId: 'calf_stretch_gastroc', cues: ['Heel stays down'] },
      { exerciseId: 'soleus_stretch', cues: ['Bend the back knee slightly'] },
      { exerciseId: 'hip_flexor_stretch_kneeling', cues: ['Tuck the tailbone before shifting forward'] },
      { exerciseId: 'hamstring_flossing', cues: ['Small, smooth range — not a deep hold'] },
      { exerciseId: 'childs_pose_breathing', cues: ['Slow, full breaths'] },
    ],
  },
  {
    id: 'ankle_dorsiflexion_routine',
    title: 'Ankle Dorsiflexion Routine',
    purpose: 'Targeted work to improve how far your ankle bends forward, which supports squat depth and landing mechanics.',
    category: 'ankle',
    categories: ['ankle', 'lower_body', 'running_readiness', 'walking_readiness'],
    targetAreas: ['Ankle', 'Calf'],
    recommendedFrequency: '3x/week',
    durationMin: 10,
    evidenceRationale: 'Limited ankle mobility may affect squat depth and landing mechanics, and ankle range of motion is trainable with consistent mobility work.',
    linkedAssessmentFinding: 'limited_ankle_dorsiflexion',
    exercises: [
      { exerciseId: 'knee_to_wall_ankle_mobilization', cues: ['Heel flat, knee travels forward'] },
      { exerciseId: 'ankle_rocks', cues: ['Warm the joint up first'] },
      { exerciseId: 'calf_stretch_gastroc', cues: ['Steady hold, breathe through it'] },
      { exerciseId: 'soleus_stretch', cues: ['Lower stretch, bent knee'] },
      { exerciseId: 'single_leg_heel_raise', dose: { sets: 2, reps: 12 }, cues: ['Full range, controlled tempo'] },
    ],
  },
  {
    id: 'hip_extension_mobility',
    title: 'Hip Extension Mobility',
    purpose: 'Opens up the front of the hip so your leg can extend further behind you during the running stride.',
    category: 'hip',
    categories: ['hip', 'lower_body', 'running_readiness'],
    targetAreas: ['Hip Flexors', 'Quads'],
    recommendedFrequency: '3x/week',
    durationMin: 12,
    evidenceRationale: 'Limited hip extension may affect stride mechanics behind the body, and hip extension range of motion improves with consistent stretching and strengthening work.',
    linkedAssessmentFinding: 'limited_hip_extension',
    exercises: [
      { exerciseId: 'hip_flexor_stretch_kneeling', cues: ['Torso tall, no low-back arch'] },
      { exerciseId: 'couch_stretch', cues: ['Ease in gradually — this one is more intense'] },
      { exerciseId: 'ninety_ninety_hip_switches', cues: ['Rotate from the hips, not the hands'] },
      { exerciseId: 'controlled_hip_cars', cues: ['Slow circles, full control'] },
    ],
  },
  {
    id: 'hip_control_and_mobility',
    title: 'Hip Control + Mobility',
    purpose: 'Combines hip range of motion with loaded control work to support balance and trunk position while running.',
    category: 'hip',
    categories: ['hip', 'problem_areas', 'lower_body'],
    targetAreas: ['Hips', 'Glutes', 'Trunk'],
    recommendedFrequency: '2–3x/week',
    durationMin: 12,
    evidenceRationale: 'Trunk and pelvic control observations are associative rather than causal, so this pairs mobility with hip/glute strengthening — the modality with the strongest evidence for supporting movement quality.',
    linkedAssessmentFinding: 'trunk_pelvic_control',
    exercises: [
      { exerciseId: 'ninety_ninety_hip_switches', cues: ['Control both directions'] },
      { exerciseId: 'glute_bridge', cues: ['Squeeze glutes at the top, not the low back'] },
      { exerciseId: 'controlled_hip_cars', cues: ['Keep the trunk quiet'] },
      { exerciseId: 'squat_pry', cues: ['Gentle pry, don\'t force it'] },
    ],
  },
  {
    id: 'low_back_mobility_reset',
    title: 'Low Back Mobility Reset',
    purpose: 'Gentle spinal movement and breathing to ease stiffness through the low back.',
    category: 'back_spine',
    categories: ['back_spine', 'problem_areas', 'full_body'],
    targetAreas: ['Low Back', 'Hips'],
    recommendedFrequency: 'As needed, up to daily',
    durationMin: 10,
    evidenceRationale: 'Dynamic mobility and breathing-paired positions increase comfort and range without the injury-prevention claims that stretching alone cannot support.',
    exercises: [
      { exerciseId: 'cat_cow', cues: ['Small, pain-free range'] },
      { exerciseId: 'childs_pose_breathing', dose: { timeSec: 90 }, cues: ['Let the breath do the work'] },
      { exerciseId: 'adductor_rockbacks', cues: ['Hinge from the hips, not the back'] },
      { exerciseId: 'thoracic_open_books', cues: ['Anchor the bottom knee'] },
    ],
  },
  {
    id: 'thoracic_mobility_for_running_posture',
    title: 'Thoracic Mobility for Running Posture',
    purpose: 'Improves rotation and extension through the upper back to support a tall, relaxed running posture.',
    category: 'upper_body',
    categories: ['upper_body', 'back_spine', 'full_body'],
    targetAreas: ['Upper Back', 'Chest'],
    recommendedFrequency: '2–3x/week',
    durationMin: 8,
    evidenceRationale: 'Dynamic thoracic mobility acutely increases range of motion without a performance cost, supporting a taller trunk position during running.',
    exercises: [
      { exerciseId: 'thoracic_open_books', cues: ['Follow your hand with your eyes'] },
      { exerciseId: 'cat_cow', cues: ['Move through the whole spine'] },
      { exerciseId: 'worlds_greatest_stretch', cues: ['Open the chest fully on the rotation'] },
    ],
  },
  {
    id: 'full_body_runner_mobility',
    title: 'Full-Body Runner Mobility',
    purpose: 'A well-rounded session touching the areas that matter most for running comfort — ankles, hips, spine, and calves.',
    category: 'full_body',
    categories: ['full_body', 'running_readiness', 'walking_readiness'],
    targetAreas: ['Ankles', 'Hips', 'Upper Back', 'Calves'],
    recommendedFrequency: '2x/week',
    durationMin: 15,
    evidenceRationale: 'Combining dynamic and static mobility with loaded control work reflects the full range of evidence-supported approaches rather than relying on stretching alone.',
    exercises: [
      { exerciseId: 'worlds_greatest_stretch', cues: ['Flow through each position'] },
      { exerciseId: 'ninety_ninety_hip_switches', cues: ['Control the switch'] },
      { exerciseId: 'thoracic_open_books', cues: ['Rotate, don\'t force'] },
      { exerciseId: 'calf_stretch_gastroc', cues: ['Steady hold'] },
      { exerciseId: 'glute_bridge', cues: ['Full squeeze at the top'] },
    ],
  },
  {
    id: 'calf_soleus_mobility_and_capacity',
    title: 'Calf/Soleus Mobility + Capacity',
    purpose: 'Combines calf and soleus stretching with loaded heel-raise work to build both range and strength.',
    category: 'lower_body',
    categories: ['lower_body', 'ankle', 'running_readiness'],
    targetAreas: ['Calf', 'Soleus', 'Achilles'],
    recommendedFrequency: '2–3x/week',
    durationMin: 12,
    evidenceRationale: 'The soleus experiences among the highest forces of any muscle during running, and calf strengthening is a cornerstone of clinical guidance for calf and Achilles capacity, so this pairs stretching with loaded reps rather than stretching alone.',
    cautionNote: 'If you have current Achilles or calf pain, ease into the heel raises and consider checking with a clinician before adding load.',
    linkedAssessmentFinding: 'calf_capacity',
    exercises: [
      { exerciseId: 'calf_stretch_gastroc', cues: ['Steady hold, both sides'] },
      { exerciseId: 'soleus_stretch', cues: ['Bent-knee version'] },
      { exerciseId: 'ankle_rocks', cues: ['Warm up the joint first'] },
      { exerciseId: 'single_leg_heel_raise', cues: ['Full range, controlled down phase'] },
    ],
  },
  {
    id: 'single_leg_control_prep',
    title: 'Single-Leg Control Prep',
    purpose: 'Builds single-leg strength and balance to support the control your body needs each time a foot hits the ground while running.',
    category: 'lower_body',
    categories: ['lower_body', 'problem_areas', 'running_readiness'],
    targetAreas: ['Hips', 'Calves', 'Balance'],
    recommendedFrequency: '2x/week',
    durationMin: 12,
    evidenceRationale: 'Single-leg strength and control work is low-risk and improves movement-quality measures, even though its link to injury outcomes is only observational.',
    linkedAssessmentFinding: 'reduced_single_leg_control',
    exercises: [
      { exerciseId: 'single_leg_heel_raise', cues: ['Balance first, height second'] },
      { exerciseId: 'glute_bridge', cues: ['Even hips, no rotation'] },
      { exerciseId: 'controlled_hip_cars', cues: ['Slow and controlled, not fast'] },
      { exerciseId: 'squat_pry', dose: { timeSec: 20 }, cues: ['Hold a stable, comfortable depth'] },
    ],
  },
];

export function getMobilityWorkout(id: string): MobilityWorkout | undefined {
  return MOBILITY_WORKOUTS.find(w => w.id === id);
}

export function getMobilityWorkoutsByCategory(category: MobilityCategory): MobilityWorkout[] {
  return MOBILITY_WORKOUTS.filter(w => w.categories.includes(category));
}

export const MOBILITY_CATEGORY_LABELS: Record<MobilityCategory, string> = {
  full_body: 'Full Body',
  problem_areas: 'Problem Areas',
  ankle: 'Ankle',
  hip: 'Hip',
  back_spine: 'Back & Spine',
  pre_run: 'Pre-Run',
  post_run: 'Post-Run',
  upper_body: 'Upper Body',
  lower_body: 'Lower Body',
  running_readiness: 'Running Readiness',
  walking_readiness: 'Walking Readiness',
};
